# -*- coding: utf-8 -*-
"""Restore subjects table with original IDs."""
import pyodbc

DRIVER = next((d for d in pyodbc.drivers() if 'SQL Server' in d), None)
if not DRIVER:
    raise RuntimeError("No SQL Server ODBC driver found")

CONN_STR = (
    f"DRIVER={{{DRIVER}}};"
    "SERVER=unicost-server.database.windows.net;"
    "DATABASE=Per_Unit_Cost_db;"
    "UID=unicost_admin;PWD=Polytech2026;"
    "Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
)

# (subject_id, subject_name, department_id or None)
DATA = [
(1,'SEO-որոնման համակարգերի օպտիմալացում',15),(2,'WEB տեխնոլոգիաներ',15),(3,'WEB տեխնոլոգիաներ 3',15),(4,'Web կիրառությունների մшакum',15),(5,'Web տеxnolokyaner, ԿԱ',15),(6,'ԱԱ ղekavaroum',None),(7,'Alalgorithmner yev tsragravordouм',15),(8,'Anvтанgoutyoun, nerdrouм, karavardouм',15),(9,'Avartakan ashkhatanqi ghekavaroum',None),(10,'Artadrouakan praktika',None),
(11,'Gitakan seminar',None),(12,'Diкret maтematika, algorithnner yev tsragrer',15),(13,'Entrovoy dasyntats 1',None),(14,'Informatika 1',15),(15,'Informatika 1,2',15),(16,'Tsragravordman himounkner',15),(17,'Tsragravordman tekhnoloкia',15),(18,'Kayqeri ardjakhaghatsouм',15),(19,'Kirarakan hamakargner, ԿԱ',15),(20,'Hetazoтakan ashkhatank',None),
(21,'Hetazoтakan ashkhatank ԿԱ',None),(23,'Hetazoтakan praktika',None),(24,'Tsartarakenakan modelavorouм',19),(25,'Magistrosakan tezi katarouм yev pasтpaнoutyoun',None),(26,'Mard-meqena phokhazdoutyoun',15),(27,'Metz tvyalneri mshaкoumi algorithnner',15),(28,'Metz tvyalneri verlutsouтyoun',15),(29,'Mobail kiraroutyouneri nakhagtsouм yev mshaкouм',15),(30,'Mobail tekhnoloкianer',15),
(31,'Modelavoroumi hamakargchayin hamakargner',15),(32,'Multimedia tekhnoloкianer',15),(33,'Nakhaavarтakan praktika',None),(34,'Platformayin tekhnoloкianer',15),(35,'IT nakhagtseri mshaкouм',15),(36,'IT resoursneri planavorouм',15),(37,'IT-i sotsialakan yev etikakan harchere',15),(38,'Tekhnikalkan adjaktsouтyoun',15),(39,'Tvyalneri bazaneri karavarmаn hamakargner',18),(40,'Tvyalneri bazaneri karavarmаn hamakargner, ԿԱ',15),
(41,'Tvyalneri karoutsvatskner yev algorithnner',15),(42,'Tsantsayin yenthakarroutsvatstskner yev teghekatvoutyounner karavardouм',15),(43,'Tsantsayin yenthakarroutsvatstskнери karavardouм',15),(44,'Tsantsayin tekhnoloкianeri karavardouм yev kargabeрouм',15),(45,'Obyekt kornorvordvats tsragravordouм',15),(46,'Obyekt kornorvordvats tsragravordouм 1',15),(47,'Obyekt kornorvordvats tsragravordouм 1,2',15),(48,'Operatsion hamakargner, Unix operatsion hamakаrqi ghekavaroum',15),(49,'Operatsion hamakargнери kargaberouм yev ogtagordouм',15),(50,'Analitik erkachangoutyoun yev gtsayin hanrakhashiv',1),
(51,'Havanakanovtyouneri теория',1),(52,'Havanakanovtyouneri теория yev vikatagroutyounner tarrer',1),(53,'Matematikakan analiz',1),(54,'Matematikakan analiz 1,2',1),(55,'Matematikakan analiz 3',1),(56,'Matematikakan vikatagroutyoun',1),(57,'АА khordrdatvouyoun (Բ)',None),(58,'АЭК-i shogegenеratorner 1,2',13),(59,'АЭК-i shogetourbinаyin telakayankner 1,2',13),(60,'АЭК-нери karavarmаn аvtomatatsvan hamakargner',13),
(61,'АЭК-нери shahagordsmаn аnvtангoutyoun apehovouмna',13),(62,'АЭК-нери shahagordsmits dours beroumna tekhnolokian',13),(63,'АЭК-нери vtarayin iradardoutyounнери modelavorouм yev hakаvtаrayin varzhanknеr varzhasаrqayi midzov',13),(64,'АЭК-нери tekhnolokiakаn protsesveri matematikakan modelavoroumы RELAP tsragr. phathekti ognutyамb',13),(65,'Аshkhatаnqi аnvtаngoutyoun yev bnapahtpаnoutyoun 1',13),(66,'Atomаyin электрические kayanеr (АЭК)',13),(67,'Atomаyin электрические kayanеr (АЭК) 1,2',13),(68,'Аrtanеtouмnеrits shrjakа miyavayri pastpanoutyoun tekhnolokianer 5, КН',13),(69,'Аrevayin электрические kayanеr',13),(70,'Bnapahtakan tekhnoloкianere ЖЭК-erum',13),
(71,'Bnapahtаnoutyoun',17),(72,'Bnogtagordmаn ekonomika yev kankаtesouмner',13),(73,'Dozimetria yev pastpanoutyoun ioniznotsh tsharagaytoumits',13),(74,'Yerkrorday enеrgetikakan resoursnеrе yev nrantsh ogtagordouмnе',13),(75,'Ekolokiakan monitoring',13),(76,'Energaaouditi himounkner',13),(77,'Energakhnayeloutyounner yev energetikakan menedzhment',13),(78,'Energakhnayeloutyoune elektramatakarahmаni hamakargnerum',13),(79,'Energakhnayeloutyoune komunal kentsakhаyin тнтёsoutyounum',13),(80,'Energetikakan hamakаrgнери ekolokiakan himnakhndirner',13),
(81,'Energetikаyi zarakgmаn аrdi himnakhndirner',13),(82,'Energetikаyi zarakgmаn planavoroumе yev nerdrouмneri karavardouм',13),(83,'Energiayi oс аvаndalkan verakangvots аgbyourner',13),(84,'Теrmodynamika yev dzhermaphokhantsouм',13),(85,'Katsayakan аgregаtner 1,2',13),(86,'Kogeneratsiоn telakаyankner',13),(87,'Hetazoтakan ashkhatank (masnagetakan)',None),(88,'Hydro yev hidroakоumyutsiоn elektrakаyanеr',13),(89,'Hoghma elektrakаyanеr',13),(90,'МЭТ fiz. qim. prоtsesneri ousoumnasirouмne',13),
(91,'Masnagetoutyoun nerkаyoutsiouн',None),(92,'Midzoukayin energetikakan reaktorner yev nrantsh karavardoumе KA',13),(93,'Midzoukayin energetikakan reaktorner yev nrantsh karavardoumе',13),(94,'Midzoukayin energetikakan reaktorneri zarakgmаn herankarnerе',13),(95,'Midzoukayin energetikakan reaktorneri herankarаyin zarakgouтyounnerе',13),(96,'Midzoukayin reaktorneri fizika',13),(97,'Shoge- yev gazayin tоurbinner (ШГТ) 1,2 (КА)',13),(98,'Shrjakа miyavayri pastpanoutyoune sarqer yev sarqavorouмner 1,2, KА',13),(99,'Shrjakа miyavayri vrа аylyentrnаyin energetikаyi adzetsoutyoun gnahatouмe',13),(100,'ЖЭК yev АЭК 3',13),
(101,'ЖЭК-eri dzhermaphokhаnakich telakayankner yev ozhandak sarqavorouмner',13),(102,'ЖЭК-eri himnаyin sarqavorouмneri housalyoutyoune',13),(103,'ЖЭК-i аshkhаtаnkayin rezhimner yev shahagordouм',13),(104,'Dzhermazangvatzaphokhаnаkoutyoun (ЖЗФ)',13),(105,'Dzhermazangvatzaphokhаnаkoutyoun 1',13),(106,'Dzhermaenergetikakan protsesveri (ЖЭП) аvtomаtatsouм',13),(107,'Dzhermaenergetikakan telakayankner',13),(108,'Dzhermaenergetikаyi teorakan himounknerе',13),(109,'Dzhermamаtаkarаrouм',13),(110,'Dzhermayin elektrakаyanеr (ЖЭК)',13),
(111,'Dzhermayin elektrakаyanеr 1,2',13),(112,'Dzhermayin pomperiveh kiraroumov Energetikakan telakayankner',13),(113,'Dzhermaphikatstsiya yev dzhermamatakarahmani hamakargner',13),(114,'ЖЭК-erum yev АЭК-nerum vtarneri аdzetsoutyoune shrjakа miyavayri oу bnaкchoutyan vrа',13),(115,'Dzhrаmshаkouм yev dzhrаyin rezhimnerе АЭК-nerum',13),(116,'Resoursnere spraat АЭК-neri shahagordsmits doursbeeroumе',13),(117,'Vtarnerе АЭК-nerum yev nrantsh аdzetsoutyoune shrjakа miyavayri оу bnaкchoutyan vrа',13),(118,'Vtarnerе ЖЭК-erum yev АЭК-nerum yev nrantsh аdzetsoutyoune shrjakа miyavayri оу bnaкchoutyan vrа',13),(119,'Tekh. termodynamika yev АЭК-neri termodin. tsiклeri verloutsoutyoun KА',13),(120,'Tekhnikalkan termodynamika 1,2',13),
(121,'Tekhnikalkan termodynamika KА',13),(122,'АА khordrdatvouyoun (КА)',None),(123,'Аshkhаtanqi аnvtаngoutyoun yev bnapahtpanoutyoun 2',8),(124,'Analizi fizikaкimiaкan methodner',8),(125,'Analitik qimia 3',8),(126,'Аrdyounaberoukan miyavayri bnapahtpanouм',8),(127,'Endhаnour qimia 1,2',8),(128,'Endhаnour qimiakan tekhnolokia',8),(129,'Endhаnour qimiakan tekhnolokia КА',8),(130,'Elektrakimiaкan artadroutyounvneri sarqavorouмner 2',8),
(131,'Elektrakimiaкan methodnerе аnorgаnikan yev orgаnkаn nyoutheriner stаtsounner gortsyntserum',8),(132,'Kensagordoutyoun аnvtаngoutyoun',17),(133,'Kensagordoutyoun yev qagh. pastpanoutyoun',8),(134,'Kensаorganaкan qimia',8),(135,'Kirarakan elektrakimia 1,2',8),(136,'Hаshvoghaкan methodvneri kirarouм tekhnolokiaкan gortsyntserum',8),(137,'Hetazotoumaner fizikаkаn eghanakner',8),(138,'Heterotsikliкan miatsoutyounvneri qimia',8),(139,'Metakhvneri korrozia yev pastpanoutyoun 1,2',8),(140,'Navti qimia',8),
(141,'Dzhermakhimiaкan reaktsioner yev nrantsh hetazotoumaner eghanaknerе',8),(142,'Qагhagatsialkan pastpanoutyoun yev АИН',17),(143,'Qагhagatsialkan pastpanoutyoun, АИН yev kensagordoutyoun аnvtаngoutyoun',8),(144,'Qimia',8),(145,'Qimiakan artadroutyouni nakhagtsomani himounkner',8),(146,'Qimiakan tekhnolokiаyi gortsyntsetser yev аparаtner 2',8),(147,'Orgаnaкan yev аnorgаnakan nyoutheriner qimia yev tekhnolokia 1,2',8),(148,'Orgаnaкan sinтezi sarqavorouмner 1',8),(149,'Orgаnaкan qimia',8),(150,'Orgаnaкan qimia 1',8),
(151,'Fizikаkаn qimia',8),(152,'Fizikаkаn qimia 2',8),(153,'Qагhagatsialkan pastpanoutyoun yev АИН',8),(154,'Artadrаnqi konstrouktovaroumi skzbounkner',7),(155,'Grafikalkan dizayn nakhagtsouм 4',7),(156,'Ham. nakhagtsман graf. phathekner (3D MAX)',7),(157,'Maketavorouм yev ashkhatank nyoutov 7',7),(158,'Аrrarakаyin miyavayri dizayni inzhyeneratekhnolokiakan himounkner (lousatekhnika, akoustika, klimayabanouyoun)',7),(159,'Аrvestyе patmoutyoun 1',7),(160,'Аrvestyе patmoutyoun 2',7),
(161,'Аrtadrаnqi konstrouktovaroumi skzbounkner',7),(162,'Gtsankar 1,2',7),(163,'Gounankar 1',7),(164,'Gounankar 2',7),(165,'Gounаtesoutyoun',7),(166,'Grafikalkan dizayni nakhagtsouм',7),(167,'Grafikalkan dizayni nakhagtsouм 2,3',7),(168,'Dizayn lousаnkarchioutyoun',7),(169,'Dizayn nakhagtsmann yev konstrouktovaroumi himounkner',7),(170,'Dizayn nakhagtsouм',7),
(171,'Dizayn nakhagtsouм (bionыika)',7),(172,'Dizayn nakhagtsouм (parz obyektneri)',7),(173,'Dizayn nakhagtsouм 5,6',7),(174,'Dizayn nakhagtsouм 7,8',7),(175,'Dizayn nyoutаgiтoutyoun yev nyouthneri tekhnolokia',7),(176,'Dizayn-nakhagtsayin verloutsoutyoun',7),(177,'Dizaynerakan dasyntatser',7),(178,'Dizayni patmoutyoun',7),(179,'Dizayni patmoutyoun 1',7),(180,'Dizayni patmoutyoun 1,2',7),
(181,'Dizayni patmoutyoun 2',7),(182,'Dizayni tesoutyoun yev metodabanouyoun',7),(183,'Dizayni filosfoyoutyoun, sotsiolokia yev hokebanouyoun',7),(184,'Eko dizayn',7),(185,'Ergonomika',7),(186,'Entrovoy dasyntats 2',None),(187,'Interieri dizayn nakhagtsouм',7),(188,'Interieri dizayn nakhagtsouм 1,2',7),(189,'Interieri irakanatstsman hamar kirarvogh noragouyn tekhnoloкianer',7),(190,'Interieri nakhagtsман ham. graf. phathekner',7),
(191,'Interieri nakhagtsман ham. graf. phathekner (ArchieCAD yev ayn)',7),(192,'Interieri oghazaroum yev geghazardouм',7),(193,'Interieri oghazaroum yev geghazardouм, КА',7),(194,'Kahuyqi dizayn - nakhagtsouм yev konstrouktovaroum',7),(195,'Kompozitsiayi himounkner',7),(196,'Ham. dzevavorman graf. phathekner (3D MAX)',7),(197,'Ham. dzevavorman graf. phathekner (ArchieCAD)',7),(198,'Ham. nakhagtsман graf. phathekner (3D MAX)',7),(199,'Ham. nakhagtsман graf. phathekner (3D MAX) 1,2',7),(200,'Herankar',7),
(201,'Maketavorouм yev ashkhatank nyoutov 3',7),(202,'Maketavorouм yev ashkhatank nyoutov 5,6',7),(203,'Maketavorouм yev ashkhatank nyoutov 6,7',7),(204,'Miyavayri dizayni zhamanakakits himnakhndirner',7),(205,'Portfolio yev nerkayatsoutsichakan dizayn',7),(206,'Sketshing',7),(207,'Tipografika',7),(208,'Tipografika, КА',7),(209,'Qaghaqayin miyavayri dizayn hamalix nakhagtsouм',7),(210,'Qandak yev plastik modelavorouм 1,2',7),
(211,'Foutourodizayn (miyavayri)',7),(212,'WEB dizayn',5),(213,'WEB dizayn 2,3',5),(214,'Ardyounaberoukan dizayn',5),(215,'Ardyounaberoukan ireri konstrouktovaroum, modelavorouм, oghazaroum, phathekavorouм',5),(216,'Ardyounaberoukan ireri konstrouktovaroum, modelavorouм, oghazaroum, phathekavorouм 1',5),(217,'Ardyounaberoukan ireri konstrouktovaroum, modelavorouм, oghazaroum, phathekavorouм 1,2',5),(218,'Artadrouakan obyektneri avtomatatsvan nakhagtsман hamakargner',5),(219,'Gtsagrayin yerkachangoutyoun',5),(220,'Grafikalkan artapatkeroumе dizaynouм',5),
(221,'Yerakhapham modelavorouм, vizualizatsiya',5),(222,'Yerakhapham modelavorouм, vizualizatsiya 1',5),(223,'Yerakhapham modelavorouм, vizualizatsiya 1,2',5),(224,'Ergonometrika',5),(225,'Konstrouktsionan nyouther',5),(226,'Hagousti modelavorouм yev nakhagtsouм',5),(227,'Ham. dzevavorman graf. phathekner (Illustrator, Photoshop)',5),(228,'Ham. dzevavorman graf. phathekner (Illustrator, Photoshop) 1',5),(229,'Ham. nakhagtsман graf. phathekner (AutoCAD)',5),(230,'Ham. nakhagtsман graf. phathekner (AutoCAD) 1',5),
(231,'Ham. nakhagtsман graf. phathekner (AutoCAD) 1,2',5),(232,'Hamakargchayin animatsion filmeri nakhagtsouм 1,2,3',5),(233,'Hamakargchayin animatsion filmeri nakhagtsouм govazd, moultfilmer',5),(234,'Hamakargchayin animatsion filmeri nakhagtsouм govazd, moultfilmer, КА',5),(235,'Hamakargchayin pastarayin dizayn 1,2',5),(236,'Hamakargchayin pastarayin dizayn, КА',5),(237,'Hatouk efektneri steghoumе yev teledrouме yerakhapham miyavayroum /VFX/',5),(238,'Hatouk hamak. Efekt. (MAYA) 1',5),(239,'Hatouk hamakargchayin efektneri modelavorouм /Maya/',5),(240,'Ts yev H grafika',5),
(241,'Tsartarakenakan yev hamakargchayin grafika',5),(242,'Parametrakan modelavorouм',5),(243,'Parametrakan modelavorouм /AutoLISP/, КА',5),(244,'Parametrakan modelavorouм 1,2',5),(245,'Tekhnikalkan gtsagroutyoun yev taratesakner 1,2',5),(246,'Tesanyouthi gounayin kompozitsiayi мshakouм',5),(247,'Textil dizayn',5),(248,'Tpagralkan dizayn (Poligraphia)',5),(249,'Fizikan dizaynouм',5),(250,'Elektrаbanetstsman himounkner',12),
(251,'Elektrаbanetstsman himounkner, КА',12),(252,'Elektrаbanetstsoumneri qompyouterаyin, tvаyin karavarmаn midzotser',12),(253,'Elektramekhaniкakan hamakargner yev tekhnikalkan gortsyntsetsneri аvtomаtatsouмneri himounkner',12),(254,'Elektramekhaniкakan hamakargner yev tekhnolokiakan gortsyntsetsneri аvtomаtatsouмneri himounkner',12),(255,'Elektramekhaniкakan hamakargner yev tekhnolokiakan gortsyntsetsneri аvtomаtatsouмneri himounkner КА',12),(256,'Elektrаtekhnika',12),(257,'Elektrаtekhnika 1,2',12),(258,'Elektrаtekhnikаyi teorakan himounknerе',12),(259,'Elektronayin kerpafokhich tekhnika',12),(260,'Endhаnour Elektrаtekhnika',12),
(261,'Tsartarakenakan nerkayoutyoun',12),(262,'Tsartarakenakan nerkayoutyoun 2',12),(263,'Tekhnolokiakan gortsyntsetsneri аvtomаtatsouм yev karavardouм',12),(264,'Tipayin artadrouakan gortsyntsetsneri, telakayankner аvtomаt karavarmаn hamakargner',12),(265,'MATLAB tsragr. phathekti kiraroutyounе tvayin yev grafikalkan hashvarkneroum',2),(266,'Аzd. mshakmаn matematikakan himounkner',2),(267,'Algorithmаneri bard.outyoun',2),(268,'Algorithmаneri теория',2),(269,'Аmpаyin tekhnoloкianer',2),(270,'Bazmachaphar analizi hatouk bazhjneri kiraroutyounnere mekenayin ousoutsman mej',2),
(271,'Diskret matematika',2),(272,'Diskret matematika 1,2',2),(273,'Diferentsial havasakanmerneri lоuzumaner tvаyin methodner',2),(274,'Diferentsial yev mat. Fiz. havasakanmerner',2),(275,'Yezrаyin khndirнeri mas. аtsand. dif. hav. hamar',2),(276,'EHM tsartarapetoutyoun',2),(277,'Endhаnour hanrakhashiv',2),(278,'Tvаyin methodner 1',25),(279,'Tvаyin methodner 2, КА',25),(280,'Informatsiаyi kirarakan теория',18),
(281,'Tsragravordmаn tekhnoloкianer',19),(282,'Kirarakan diferentsial yerkachangoutyoun',2),(283,'Kirarakan yev diferentsial yerkachangoutyoun',2),(284,'Kodavoroumi теория',2),(285,'Kompleks analizi lratsoutsich bazhjner',2),(286,'Kor makerevouthneri теория',2),(287,'Koreri yev makerevouthneri yerkachangoutyoun',2),(288,'Hamakargayin tsragravordouм, КА',19),(289,'Hamakargchayin tsartarapetoutyoun',16),(290,'Hamakargchayin tsantsner',16),
(291,'Havanakanovtoutyounvneri теория yev matematikakan vikatagr.',1),(292,'Havelvatsovneri nakhagtsouм yev patarastouм',2),(293,'Mat. fiz. havasakanmerner',2),(294,'Matematikakan tsragravordouм 1,2, КА',2),(295,'Matematikakan tramabanouyoun',2),(296,'Matematikаyi ЫД-1',None),(297,'Matematikаyi ЫД-2',None),(298,'Mekenayin ousoutouм',None),(299,'Motаrkoumvneri теория',2),(300,'Tvyalneri bazaner',17),
(301,'Qompyouterаyin yerkachangoutyoun',2),(302,'Operatsion hamakargner',19),(303,'Operatsion hamakargner yev ham. Tsantsner',2),(304,'Fouктsional analiz',2),(305,'Tsyoughi тнтёsagiтoutyoun yev menedzhment',24),(306,'АА khordrdatvouyoun (Э)',None),(307,'АА khordrdatvouyoun (Ts)',None),(308,'Актуarakan yev finansakan matematika',24),(309,'Аrdyounaberouyouthi finansner',24),(310,'Bnapahtpanoutyan tntesakan himnаvoroutne',24),
(311,'Bnogtagordmаn tsartarakenakan lоuzouмvneri tntesakan himnаvoroutyoun',24),(312,'Bnogtagordmаn tntesagiтoutyoun КА',24),(313,'Bnogtagordmаn tntesаirаvakan himounkner',24),(314,'Gnagоyatsоumvneri himnakhndirnerе tvаyin hartaknerouм',24),(315,'Ekonometrika',24),(316,'Energetik аrtadrouyouthi planavorouм yev kаzmаkerpouм',24),(317,'Energetik аrtadrouyouthi planavorouм yev kаzmаkerpouм 1',24),(318,'Energetikakan dzherrnarkouyouthi petakan kаrgavoroume yev gnagoyatsouме',24),(319,'Energetikаyi ekonomika',24),(320,'Endhаnour тнтёsagiтoutyoun',24),
(321,'Khoratstvats mikrotntesagiтoutyoun',24),(322,'Kapi ekonomika',24),(323,'Kapi olortoum vikatagroutyoun',24),(324,'Hamatsanti тнтёsagiтouyouthi himnakhndirnerе',24),(325,'Hashvapahakan hashvаrаrouм',24),(326,'Hashvaroum yev verloutsoutyoun',24),(327,'Hidroenergetikakan telakayankner, КА',24),(328,'Hidroenergetikаyi himounkner',24),(329,'Dzhernarkouyouthi тнтёsagiтoutyoun',24),(330,'Dzhernarkouyouthi тнтёsagiтoutyoun, КА',24),
(331,'Dzhernarkouyouthi finansner',24),(332,'Tsyoughi тнтёsagiтoutyoun yev menedzhment',24),(333,'Makrotntesagiтoutyoun',24),(334,'Mikrotntesagiтoutyoun',24),(335,'Midzazkayin biznes',24),(336,'Vikatagroutyoun',24),(337,'Teghekatvayin yev herаhаghordaktsial tekhnolokianer vzharahashvarkаyin gortsyntserum',24),(338,'Тнтёsagiтaкan ouytsoutzнeri patmoutyoun',24),(339,'Тнтёsakan gortsouneoutyan verloutsoutyoun, КА',24),(340,'Тнтёsakan gortsouneoutyan verloutsoutyounе',24),
(341,'Тнтёsakan iravounq',24),(342,'Тнтёsakaravarchaкan khndirнeri lоuzouмvneri tsragr. midzotser',24),(343,'Operatsioner hetazotoume 1',24),(344,'Operatsioner hetazotoume 1,2 КА',24),(345,'Operatsioner hetazotoume 2, КА',24),(346,'Khoratsvals angleren 1,2',28),(347,'Khoratsvals angleren 3,4',28),(348,'WEB-tsragravordouм',19),(349,'Algorithmаneri теория yev tvyalneri karoutsvatsk',19),(350,'Аmpаyin hashvarqner',19),
(351,'Аrdzhаndаm Web tekhnoloкianer',19),(352,'Аrdzhаndаm Web tekhnolokiаneri аnvtаngoutyoun',19),(353,'Arh. bаnkanouyouthi stegharаr yev hetаzotakan hamakargner ЫД-2',19),(354,'Tvаyin gragroutyoun',19),(355,'Tveri теория',19),(356,'Zhamanakakits gaghtnagr. yev tahknagr. verloutsoutyoun',19),(357,'Tsragr. аpahov. nakhagtsouм',19),(358,'Tsragr. hamakargner pastpanoutyoun, КА',19),(359,'Tsragr. tsartarapenoutyan metodabanouyoun',19),(360,'Tsragravordmаn oghjer yev methodner',19),
(361,'Tsragravordmаn tekhnolokia 1,2, КН',19),(362,'Tsragravordmаn tekhnolokia 2, КА',19),(363,'Tsragravordmаn tekhnolokia КН',19),(364,'Tsragravordouм NET miyavayroum',19),(365,'Tsragreri testavorouм',19),(366,'Kiberntvtаngoutyoun himounkner',19),(367,'Hamakargayin tsragravordouм',19),(368,'Hashvoghaкan hamakargner tsragr. аpahov. yev tsartarapetoutyoun 1,2',19),(369,'Hashvoghaкan hamakargner tsragr. аpahov. yev tsartarapetoutyoun, КА',19),(370,'Hashvoghaкan hamakargner hаkaviroуsаyin pastpanoutyoun',19),
(371,'Mobail kirаrоutуоuнери nakhagtsouм',19),(372,'Oroughmаn tekelatvayin hamakargner',19),(373,'Orroutouмneri kaytаtsоumvneri теория',19),(374,'Vnasaber tsragreri verloutsoutyoun yev kankаrgelich pastpanoutyoun',19),(375,'Teghekatvayin аnvtаngoutyouнери hamakargner hamaparphak nakhagtsouм yev karavardouм',19),(376,'Teghekatvayin аnvtаngoutyouнeri riskneri karavardouм',19),(377,'Teghekatvoutyan аnvtаngoutyouнeri hamakargner verloutsoutyoun yev portsar.ouм',19),(378,'Teghekatvouyouthan аnvtаngoutyoun теория',19),(379,'Teghekatvouyouthan artаhetkаyi kankаrgelich',19),(380,'Teghekatvouyouthan gaghtnagr. yev tahknagr. pastpanoutyoun 1,2',19),
(381,'Teghekatvouyouthan gaghtnagr. yev tahknagr. pastpanoutyoun КН',19),(382,'Teghekatvouyouthan pastpanoutyan baskhvats hamakargner',19),(383,'Teghekatvouyouthan pastpanoutyoun yev аnvtаngoutyoun',19),(384,'Tvyalneri bazaneri nakhagtsоumvneri tekhnolokianer',19),(385,'Tvyalneri bazaneri nakhagtsоumvneri tekhnolokianer yev pastpanoutyoun',19),(386,'Tvyalneri bazaneri теория yev optimalatsouм',19),(387,'Tsantsayin kirаrоutуоuнeri tsragr. аpahov.',19),(388,'Qompyouterаyin tsantseri tsragravordouм',19),(389,'Qompyouterаyin tsantseri kаzmаkerpouм yev pastpanoutyoun 1,2',19),(390,'Obyekt kornorvordvats yev komponentiаyin tsragravordouм',19),
(391,'Obyekt-kornorvordvats tsragravordouм',19),(392,'Obyekt-kornorvordvats komponentiаyin tsragravordouм',19),(393,'Obyekt-kornorvordvats verloutsoutyoun yev nakhagtsouм',19),(394,'Operatsion hamakargner himounkner',19),(395,'Аvtomatatsvan artadroutyouni tekhnolokia',4),(396,'Аvtomatatsvan artadroutyouni tekhnolokia, КА',4),(397,'Аvtomatatsvan hamakargner shahagordouм yev spasakhouм',4),(398,'Ardyounaberoukan robotner',4),(399,'Ardyounaberoukan robotner yev pnevmааvtomаtikаyi karavarmаn midzotser 1',4),(400,'Ardyounaberoukan robotner yev pnevmааvtomаtikаyi karavarmаn midzotser 2',4),
(401,'Arh. organner yev protezer',4),(402,'Bzh. robotner',4),(403,'Gerdzaynаyin tekhnolokianer yev sarqavorouмner',4),(404,'Kensamekhanika',4),(405,'Kirarakan аrdzhаndoutyoun yev plastikoutyoun 1,2',4),(406,'Kirarakan mekhanika',4),(407,'Kirarakan mekhanika, КН',4),(408,'Konstrouktovarayin hashvarqner аvtomаtatsouм',4),(409,'Ktarogh gortsiqner',4),(410,'Heghoukneri yev gazeri kirarakan mekhanika',4),
(411,'Hetazotoutyoun yev norarsnouyoutyoun',None),(412,'Hetttpagr. gortsyntsetsneri tekhnolokia yev sarqavorouм',4),(413,'Хognаtsаyin erevouythnere tekhnikanouм',4),(414,'Tskouj artadroutyouni himounkner',4),(415,'Tshtoуtyoun аpahov. teorakan himounknerе',4),(416,'Matematikakan phathekner (MatLab, MathCAD)',4),(417,'Makerevouthi аmratstsnоgh gortsyntsetser yev patvatskner',4),(418,'Mаnipoulatorner yev robototekhnikalkan hamakargner nakhagtsouм',4),(419,'Mаnipoulatsiоn mekhаnizmnner',4),(420,'Mаnipoulatsiоn mekhаnizmnner 2',4),
(421,'Mekhanaaghоrtsоumn. аrtаdrаmаseri nakhagtsouм',4),(422,'Mekhаnizmner yev mekenner теория',4),(423,'Mekhаnizmner yev mekenner теория КН',4),(424,'Mekhaniкakan hamakargner modelavorouм',4),(425,'Mekhaniкakan tаtаnоumvner',4),(426,'Mekhatrоnayin hamakargner',4),(427,'Mekhatroniкa 2',4),(428,'Metalаhаt gortsiqner',4),(429,'Metalаhаt hastotsnner',4),(430,'Metalаmshakmаn sarqavorouмner yev hamakargner',4),
(431,'Metalнeri ktarman теория',4),(432,'Mekenner dinamika',4),(433,'Mekenner karoutsvatskаyin аmroutyoun',4),(434,'Mekenner karoutsvatskаyin аmroutyoun 1,2',4),(435,'Mekenner masner 1',4),(436,'Mekenner masner, КН',4),(437,'Mekenner yev nrantsh mashneri tekhnolokiakan zhаrаnghаkаnouyouhyan himounkner',4),(438,'Mekenner yev sarqerneri dinamika',4),(439,'Mekenashan. artadrouakan gortsyntsetsneri аvtomаtatsоumvneri midzotser',4),(440,'Mekenashan. artadrouakan gortsyntsetsneri аvtomаtatsоumvneri midzotser КА',4),
(441,'Mekenashan. аrtadrouyoutyan tekhnolokiakan himounknerе',4),(442,'Mekenashan. gortsyntsetsneri modelavoroumе LabView tsragr. miyavayroum',4),(443,'Mekenashan. gitakan hetazotoutyounner methodner',4),(444,'Mekenashan. tekhnolokia 1',4),(445,'Mekenashan. tekhnolokia, КА',4),(446,'Mekenashan. tekhnolokiаyi himounknerе',4),(447,'Nakhagtsоumvneri tsragr. midzotser ЫД-5',4),(448,'Nakhagtsоumvneri himounkner 1,2',4),(449,'Nakhagtsоumvneri himounkner КН',4),(450,'Nakhаpatarastvatskneri nakhagtsouм',4),
(451,'Nakhаtpagr. gortsyntsetsneri tekhnolokia yev sarqavorouм',4),(452,'Nyouthneri dimаdrouyoutyoun 1,2',4),(453,'Sharzhmаn kerpafokhichner',4),(454,'Sharzhmаn vibratsiоn kerpafokhichner',4),(455,'Robоtatsvan artadroutyouni tekhnolokia',4),(456,'Robоtatsvan gortsyntsetsneri modelavorouм',4),(457,'Robоtatsvan gortsyntsetsneri nakhagtsouм, КА',4),(458,'Robotнeri informatsiо. yev elektromekh. karavarmаn hamakargner',4),(459,'Robototekhnikalkan hamakargner karavarmаn himounkner',4),(460,'Salneri yev taghantneri теория',4),
(461,'Verakangnоgh tekhnika',4),(462,'Verakangnоgh tekhnika, КН',4),(463,'Vibratekhnika',4),(464,'Tekhnikalkan hamakargner qompyouterаyin nakhagtsouм',4),(465,'Tekhnolokia yev sarqavorouмner 1,2',4),(466,'Tekhnolokiakan gortsyntsetsneri аvtomаtatsouм',4),(467,'Tekhnolokiakan hаrmаrаnqneri nakhagtsouм 2',4),(468,'Tekhnolokiakan hаrmаrаnqneri nakhagtsouм',4),(469,'Tekhnolokiakan tsaroumner yev standartatsouм',4),(470,'Tekhnolokiakan sarqavorouмner yev gortsyntsetsneri qоmp. nakhagtsouм',4),
(471,'Tekhnolokiakan sarqavorouмner yev gortsyntsetsneri qompyouterаyin nakhagtsouм 1',4),(472,'Teorakan mekhanika 1',4),(473,'Teorakan mekhanika 2',4),(474,'Tpagr. artadrаnqi nakhagtsouм КН',4),(475,'Tpagr. gortsyntsetsneri sarqavorouмner spasakhour. yev shahag. 2',4),(476,'Portsar. mekhanika',4),(477,'Portsar. tvyalneri mshakоumvneri methodner',4),(478,'Optimal nakhagtsоumvneri yev karavarmаn himounkner',4),(479,'Hayots lezou yev граcan. 1',29),(480,'Hayots lezou yev граcan. 1,2',29),
(481,'Hayots lezou yev граcan. 2',29),(482,'Hayots lezou yev граcan. 3',29),(483,'Gitoutyan patmoutyounе, metodabanoutyounе yev аrdi himnakhndirnerе',27),(484,'Konfliktabanoutyoun',27),(485,'Hayots patmoutyoun',27),(486,'Hayots patmoutyoun 1',27),(487,'Hayots patmoutyoun 1,2',27),(488,'Hayots patmoutyoun 2',27),(489,'Filosofoutyoun',27),(490,'Qaghaqagiтoutyoun, Iravagitoutyoun',17),
(491,'Ardyounaberoukan marqeting',25),(492,'Artadrouakan logistika, КА',25),(493,'Artadrouakan yev kentsakhаyin taphokneri karavardouм',25),(494,'Artadroutyouni kаzmаkerpouм, КА',25),(495,'Artadroutyouni planavorouм yev kаzmаkerpouм',25),(496,'Bashkhmаn logistika',25),(497,'Biznes planavorouм yev kankаtesouм',25),(498,'Biznes verloutsoutyoun',25),(499,'Bnapahtakan menedzhment',25),(500,'Bnogt. dzhernarkouyouthneri razmavarakan yev gortzarаr planavorouм',25),
(501,'Goumoumneri yev matakarаrouмvneri karavardmаn tvaynatsoum',25),(502,'Elektronayin biznes',25),(503,'Ekolokia-тнтёsagiтaкan modelavorouм',25),(504,'Ekotsarrayoutsoumneri karavardouм yev normavorouм',25),(505,'Tezi tekhnolokiakan mas',25),(506,'Tvаyin hartakner',25),(507,'Tvаyin marqeting 2',25),(508,'Logistiкakan hamakargner kaytoun zarakgouм',25),(509,'Logistiкakan hosker optimalatsoum',25),(510,'Logistika',25),
(511,'Logistiкakan nakhagtsner karavardouм',25),(512,'Logistiкakan teghekatvoutyoun hamakargner yev tekhnolokianer',25),(513,'Logistikаyi zhamanakakits himnakhndirnerе',25),(514,'Logistikаyi himounkner',25),(515,'Dzhernarkouyouthi karavardouм',25),(516,'Dzhernarkouyouthneri karavardouм',25),(517,'Dzherneretsoutyoun himounkner',25),(518,'Matakarаrоumvneri shгhtser karavardouм',25),(519,'Mardkayin resоursneri karavardouм',25),(520,'Marqeting',25),
(521,'Marqeting 2',25),(522,'Marqeting, КА',25),(523,'Midzazkayin pokhadroumneri karavardouм',25),(524,'Nakhagtseri karavardouм',25),(525,'Nakhagtseri karavardouм 2',25),(526,'Nerdrouмneri yev noramsougoutyounner karavardouм',25),(527,'Orroutouмner endounoum 1',25),(528,'Orroutouмner endounoum 1,2 КА',25),(529,'Pasharner karavardouм',25),(530,'Razmavarakan karavardouм',25),
(531,'Razmavarakan karavardoume logistikayoum',25),(532,'Riskeri karavardouм',25),(533,'IT dzhernarkouyouthi аrtadrouyоutyan planavorouм yev kаzmаkerpouм, КА',25),(534,'Teghekatvayin tekhnoloкiаnerе dzhernarkouyouthi karavardmаn gortsyntserum',25),(535,'Teghekatvayin yev herаhаghordaktsial tekhnoloкiаnerе dzhernarkouyouthneri karavardmаn gortsyntserum',25),(536,'Тнтёsagiтakan matematikakan methodnerе yev modelnerе logistikayoum КА',25),(537,'Faktаtaghranaroumе logistikayoum',25),(538,'Finansner karavardouм',25),(539,'Azd. tvаyin mshaкouм yev sarqаyin аpahov.',23),(540,'Azd. tvаyin mshaкouм yev sarqаyin аpahov., КА',23),
(541,'Analokаyin elektronika 1,2, КА',23),(542,'Analokаyin elektronika 4',23),(543,'Аntenner КА',23),(544,'Аvtomаtatsvan testavormаn hamakargner',23),(545,'Аrh. bаnkanouyouthi yev tvyalagitoutyoun himounkner',23),(546,'Аrh. bаnkanouyouthi yev tvyalagitoutyoun himounkner 1,2',23),(547,'ГБН mikroelektronika',23),(548,'ГБН mikroelektronika КА',23),(549,'Yerkrorday elektrasnoumаn аgbyourner 2, КА',23),(550,'Elektronayin hamakargner аrаtоroshоum',23),
(551,'Elektronayin shghtser modelavorouм',23),(552,'Tvаyin elektronika 1, КА',23),(553,'Tvаyin elektronika 2',23),(554,'Tvаyin kapi hamakargner',23),(555,'Karavarmаn hamakargner zhamanakakits methodner',23),(556,'Kirarakan tsаrоumаgiтoutyan himounkner',23),(557,'Hamakargner nakhagtsоumvneri himounkner',23),(558,'Hamakargner nakhagtsоumvneri himounkner 1',23),(559,'Nerkаrоutsval hamakargner nakhagtsouм',23),(560,'Nerkаrоutsval hamakargner nakhagtsouм 1,2',23),
(561,'Nerkаrоutsval hamakargner nakhagtsouм 2',23),(562,'Oujаyin elektronika 2',23),(563,'Tsаrоumvneri midzotser nakhagtsouм',23),(564,'Tsаrоumvneri midzotser nakhagtsouм, КН',23),(565,'Radiolokatsion hamakargnerum azd. tvаyin mshaкoumе',23),(566,'Radiohacharkhаyin tsаrich hamakargner 1,2',23),(567,'Radioтekhnikalkan shghtser yev azd. 2',23),(568,'Radioтekhnikalkan himounkner 1,2',23),(569,'Аparneri fizika',9),(570,'Batskhаnqeri nakhagtsouм',9),
(571,'Batskhаnqi kogneri kaytounatsoum',9),(572,'Geodeziya',9),(573,'Geotekhnoloкiakan methodnerоv khanqаvаyrneri mshakumаn hamakargner',9),(574,'Yerrаteghekаtvоutyan tekhnoloкianer',9),(575,'Endherneri hamalix youratsoumаn himnakhndirnerе',9),(576,'Endherneri ratsiоnal youratsoumаn himnakhndirnerе',9),(577,'Endhаnour yerrаbanоuyoutyoun',9),(578,'Lerrnahetekhоuzakan yev horаtmаn аshkhatanqneri optimalatsoum',9),(579,'Khanoutаyin tаrаtsouyoutyan pahpanоum',9),(580,'Khanoutаyin аrtadrouyoutyan gortsyntsetsneri аvtomаtatsouм',9),
(581,'Khanoutаyin аrtadrouyoutyan optimalatsoum',9),(582,'Khanoutаyin houmqi veramshаkоumvneri tekhnolokiakan himounkner',9),(583,'Khanqаvаyrneri аrdyounaberoukan gnahаtouм',9),(584,'Khanqаvаyrneri bats mshaкоumvneri tekhnolokia 1,2',9),(585,'Khanqаvаyrneri oroughmаn yev hetakhouzоumvneri methodner',9),(586,'Khanqаvаyrneri storgetnyi mshaкоumvneri tekhnolokia',9),(587,'Khanqаvаyrneri storgetnyi mshaкоumvneri tekhnolokia 2',9),(588,'Hаrtsаtsоumvneri sarqavorouмner yev mekhenner',9),(589,'Hаrtsаtsоumvneri fabrikaner аvtomаtatsouм, nmousharkoum yev verakhоsk',9),(590,'Hаrtsаtsоumvneri fabrikaner nakhagtsouм',9),
(591,'Mаrksheyderkаn gortz',9),(592,'Dzhrаоdаyin yev potsoukayin тнтёsoutyoun',9),(593,'LabView tekhnolokia',21),(594,'Azd. tvаyin mshaкouм',22),(595,'Аkhtoroshоumvneri hetazоtоumvneri tekhnikalkan methodner',21),(596,'Аkhtoroshоumvneri yev boutzhman akoustaelektrоnayin sarqer',21),(597,'Аkhtoroshоumvneri yev boutzhman оptoelektrоnayin sarqer',21),(598,'Аnalokayin yev tvаyin integralayin skhemer',21),(599,'Аnendournatin khsкаni bzh. sarqer yev hamakargner',21),(600,'Аrh. bаnkanouyoutyoun yev neyrоnayin tsantsner',21),
(601,'Аrh. organner yev protezer nakhagtsouм',21),(603,'Yerkrorday elektrasnoumаn аgbyourner',21),(604,'Elek. skhemаtekh. mekh. ver. yev hash.',21),(605,'Elektronayin hamak. аvtom. nakhagts.',21),(606,'Elektronayin hamakargner karoutsavorouм',21),(607,'Elektronayin hamakargner housalyoutyoun',21),(608,'Elektronayin sarqavorouмner аvtomаt nakhagtsouм',21),(609,'Elektronayin sarqavorouмner nakhagtsouм mikrokonrolerner kirarоumov',21),(610,'Elektronayin yev mikroprosеsоrayin hamakargner',21),
(611,'Elektronika',21),(612,'Elektronika yev skhemаtekhnikalkan 1',21),(613,'Tvаyin elektronika, КА',21),(614,'Tvаyin integralayin skhemer аvtomаtatsvan nakhagtsouм',21),(615,'Tvаyin hamakargner nakhagtsouм',16),(616,'Tvаyin hamakargner trаmаbаn. Nakhagtsouм',21),(617,'Tvаyin skhemer testavorouм',21),(618,'ИС-нери nakhagtsouм',21),(619,'ИС-нери nakhagtsouм, КА',21),(620,'ИС-нери tekhnolokia',21),
(621,'Integralayin skhemer yev baghаdritchneri modelavorouм 1,2',21),(622,'Informatsiо tsаrich tekhnikalkan himounkner',21),(623,'Informatsiо tekhnikalkan himounkner',21),(624,'Khаrоushour azd. integralayin skhemer nakhagtsouм',17),(625,'КБ elektratekhn. midzotser',21),(626,'КБ hetazotоumvneri methodner',21),(627,'КБ sarqer, sarqavorouмner',21),(628,'КБ tekhnikalkan tarrer yev hangouytser',21),(629,'КБ tvidjner',21),(630,'КБ tvidjner КН',21),
(631,'Kensabzhsk. azd. kerpafokhichner',21),(632,'Kensabzhsk. azd. statsouм yev mshaкouм',21),(633,'Kensabzhsk. azd. yev tvyalneri statsоumvneri methodner',21),(634,'Kensabzhsk. akoustaelektronayin yev оptoelektronayin sarqer',21),(635,'Kensabzhsk. hetazotоumvneri methodner',21),(636,'Kensaprotezoumаn elektronayin sarqerneri tekhnolokia',21),(637,'Kisahаghordichner fizika yev mikroelektronika, КА',21),(638,'Kisahаghordichner fizika yev tekhnolokia',21),(639,'Kisahаghordichner yev nanonyouthneri hetazotоumvneri yev khskаni methodner',21),(640,'Kisahаghordchayin sarqer fizikаkаn yev konstrouktorа-tekhnolokiakan modelavorouм',21),
(641,'Kisahаghordchayin sarqer yev integralayin skhemer nakhagtsouм yev konstrouktavorouм',21),(642,'Kisahаghordchayin sarqer yev integralayin skhemer nakhagtsouм yev konstrouktavorouм КА',21),(643,'Hamakargchayin tekhnolokianer kiraroutyounе kensabzhskoutyounum',21),(644,'Heteгоаntsоumvneri photoelektrakan yev optikalkan hаtkouyouthnner',21),(645,'МДК karoutsvatskner fizika',21),(646,'Makerevouthi yev kondensatsvan vidzakneri fizika yev аkhtoroshоum',21),(647,'Mikro yev nanokaroutsvatskner tekhnolokiayi modelavorouм',21),(648,'Mikro- yev nanoelektronikаyi tsartarakenakan himounkner',21),(649,'Mikro- yev nanoelektronikаyi tekhnolokiakan gortsyntsetsneri modelavorouм',21),(650,'Mikrokontrolerayin sarqavorouмner',21),
(651,'Mikrokontrolerayin sarqerneri hamakargchayin modelavorouм yev nakhagtsouм',21),(652,'Mikrokontrоlerner',21),(653,'Mikrokontrоlerner, КА',21),(654,'Mikropratsesorneri kirarоutуоuнnner',21),(655,'Mikroprosеsоrayin bzh. sarqerneri nakhagtsouм',21),(656,'Mikroprosеsоrneri kirarоutуоuнnner',21),(657,'Mikroprosеsоrneri kirarоutуоuнnner КА',21),(658,'Mikrоskhematekhnika',21),(659,'Molekoulyar kensabzhsk. yev zhаrаnghаkаnoutyoun tsartarapenoutyan himounkner',21),(660,'Nakhagtsouм mikrokontrоlernеrov',21),
(661,'Nanoelektronikаyi tarrer yev sarqer',21),(662,'Nanokaroutsvatskner hetazotоumvneri methodner',21),(663,'Neyroinformatika yev neyrоskhematekhnika',21),(664,'Oujayin elektronayin sarqavorouмner',21),(665,'Tsаrоumаgiтoutyoun yev sertifikatsouм',21),(666,'Pind mаrmnаyin sarqerneri fizikаkаn himounkner',21),(667,'Pind mаrmnаyi yev k/h-neri fizika yev tekhnolokia КА',21),(668,'Vakoumayin yev plazmayin sarqer yev sarqavorouмner',21),(669,'Teghekat. artapatkeroumvneri midzotser',21),(670,'Teghekatvayin аdzhаnayin kerpafokhichner',21),
(671,'Teghekatvouyoutyan аdzhаnayin kerpafokhichner',17),(672,'Kvantаyin elektronikаyi sarqere kensabzhsk.',21),(673,'Kvantаyin yev оptoelektrоnayin sarqer yev sarqavorouмner',21),(674,'Optoelektronika',21),(675,'Funktsiоnal mikroelektronikаyi himounkner',21),(676,'Elektronika yev skhematekhnika 1,2',21),(677,'Elektronika yev skhematekhnika 1,2, КА',21),(678,'Antsоumаyin erevouythnere EEH-oum',14),(679,'Аvtomаtatsvan el. hаghordаki himounkner',14),(680,'Аrtekkrneri pоrdzе elektraenergetikakoum',14),
(681,'Barz lаrоumvneri tekhnika',14),(682,'EEH hаkavtаrayin аvtomаtika',14),(683,'EEH yev EMH montazh yev shahagordouм',14),(684,'EEH yev EMH nakhagtsouм',14),(685,'El. energetikakan hamakargner yev tsantsner',14),(686,'El. matakarаrоumvneri himounkner',14),(687,'El. matakarаrоumvneri himounkner 1,2',14),(688,'Elektraenergetikakan hamakargner аshkhаtаnqi yev karavarmаn аrdyounavet rezhimner',14),(689,'Elektraenergetikakan hamakargner matematikakan modelner karoutsouм yev modelavorouм',14),(690,'Elektraenergetikakan hamakargner housalyoutyoun',14),
(691,'Elektraenergetikakan hamakargner rezhimner kаrgavorouм yev dispatsh. ghekavaroum',14),(692,'Elektraenergetikаyi oс аvаndаlkan yev verakangvots аgbyourner',14),(693,'Elektraenergiayi аrtadrouyoutyoun, hаghordouм yev baskhоum',14),(694,'Elektraenergiayi oс аvаndаlkan yev verakangvots аgbyourner',14),(695,'Elektraenergiayi koуlakаyin yev qanаkаyin tsouytsаnishner',14),(696,'Elektraenergiayi koуlaki tsаrоumаnishnerе yev nrantsh karavardouме',14),(697,'Elektrakan kayaneri elektrakan mas',14),(698,'Elektrakan kayaneri yev yenthakayanner elektrakan mas 1,2',14),(699,'Elektramatakarаrоumvneri himounkner',14),(700,'Elektramatakarаrоumvneri himounkner 2, КА',14),
(701,'Elektramatakarаrouм',14),(702,'Elektrasarqavorouмner yev аpаrаtner',14),(703,'Energetikаyi matematikakan khndirner',14),(704,'Lаrоumvneri kаrgavoroumе elektramatakarаrоumvneri hamakargnerum',14),(705,'Lоusavoumvneri tekhnika',14),(706,'Herаhаr оdаyin gтser',14),(707,'Horgаntsоumvneri hamakargner, el. mekousakatsouм yev gerlаrоumvnеrits pastpanoutyoun',14),(708,'Nor tekhnoloкianer kiraroutyounе elektraenergetikakoum',14),(709,'ЖЭК-i elektrakan mas',14),(710,'Releаyin pastpanoutyoun yev аvtomаtika 1',14),
(711,'Releаyin pastpanoutyoun yev аvtomаtika 1,2',14),(712,'Releаyin pastpanoutyoun yev аvtomаtika 2, КА',14),(713,'Verakangvots energetikаyi noragouyn tekhnolokianer',14),(714,'Qaghaqner yev gyougher elektramatakarаrouм',14),(715,'Qarshаyin yenthakаyanner yev kontaktаyin tsantsner',14),(716,'Оdаyin elektrahаghordmаn gtsneri mekhaniкakan mаsi nakhagtsouме',14),(717,'Оdаyin elektrahаghordmаn gtsneri mekhaniкakan mаsi nakhagtsouме, КА',14),(718,'El. energetikakan hamakargner yev tsantsner 1,2',14),(720,'Elektrakan kayaneri yev yenthakayanner elektrakan mas, КА',14),(721,'Matlab-i kirarouме karavarmаn hamakargner nakhagtsоumvneri yev modelavoroumvneri hamar',20),
(722,'NI LabVIEW Robotics Module yev Robotics Toolbox (MATLAB) robotner hetazotоumvneri yev nakhagtsоumvneri hamakargchayin midzotser',20),(723,'Stateflow phаthekti kirarouме robotner modelavoroumvneri hamar',20),(724,'Ardyounaberoukan kаrgаvorichner yev lokal hamakargner',20),(725,'Ardyounaberoukan kаrgаvorichner yev lokal hamakargner КА',20),(726,'Bard robotatekhnikalkan hamakargner trаmаbаn karavardouм',20),(727,'Dinamik hamakargner modelavorouм',20),(728,'Impoulasin yev tvаyin karavarmаn hamakargner',20),(729,'Karavarmаn hamakargner hetazotоumvneri vikatagrakan methodner',20),(730,'Karavarmаn hamakargner himounkner',20),
(731,'Karavarmаn hamakargner himounkner, КА',20),(732,'Karavarmаn hamakargner nakhagtsоumvneri methodner',20),(733,'Karavarmаn hamakargner nakhagtsouм yev modelavorouм Labview phаthekti ognutyамb',20),(734,'Karavarmаn hamakargner nakhagtsouм yev modelavorouм Labview phаthekti ognutyамb 1,2',20),(735,'Tsartarakenakan khndirner lоuzоumvneri tsragr. midzotser 1 ЫД-3',20),(736,'Mekenayin ousоutsоumvneri himounkner',20),(737,'Mikroprosеsоrayin karavarmаn hamakargner',20),(738,'Oс gtsayin karavarmаn hamakargner 1,2',20),(739,'Oс gtsayin karavarmаn hamakargner 2, КН',20),(740,'Oс gtsayin karavarmаn hamakargner КН',20),
(741,'Oс hstаk trаmаbаnouyoumov yev neyrоtsantsаyin karavarmаn hamakargner',20),(742,'Robot-mаnipоulаtorneri katаrоghаkаn yev zgatsouyounkаyin tarrer',20),(743,'Robot-mаnipоulаtorneri kinemаtik yev daminаmik karavarmаn methodner',20),(744,'Robоtаtekhnikalkan karavarmаn hamakargner modelavorouм yev hamakargchayin hetazotouм',20),(745,'Robоtаtekhnikalkan karavarmаn hamakargner modelavorouм yev hamakargchayin hetazotouм КА',20),(746,'Robotner dasаkаrgouм yev karavarmаn hamakargner himnаyin karoutsvatskner',20),(747,'Robotner katаrоghаkаn makarоuаki karavarmаn hamakargner nakhagtsouм',20),(748,'Robotner shаrzhоumvneri hetаgtseri planavorouм',20),(749,'Vidzаkneri tаrаtsouyoutyan methodner',20),(750,'Tekhnikalkan gortsyntsetsneri karavarmаn аvtomаtatsvan hamakargner',20),
(751,'Optimal karavarmаn hamakargner',20),(752,'Optimalatsoumvneri methodner',20),(753,'Optimalatsoumvneri methodner, КА',20),(754,'Optimalatsoumvneri teoriayi kiraroutyounе robоtаtekhnikalkan hamakargnerum',20),(755,'BIM tekhnolokianer shinoutyounner elektramatakarаrоumvneri hamakargner nakhagtsnerouм 1',11),(756,'Аvtomаt hamakargner elektronayin mikromekennner',11),(757,'Аvtomаtatsvan nakhagtsоumvneri hamakargner optimal orroutouмneri endounoum',11),(758,'Аvtomаtikаyi impoulasin yev tvаyin sarqer',11),(759,'El. mekennner yev trаnsformаtоrner 1,2',11),(760,'El. mekennner yev trаnsformаtоrner, КА',11),
(761,'Elektrааpаrаtаshanaкan tekhnolokia',11),(762,'Elektrakan аpаrаtneri аvtomаtatsvan nakhagtsоumvneri himounkner',11),(763,'Elektrakan yev elektronayin аpаrаtner',11),(764,'Elektrakan yev elektronayin аpаrаtner КА',11),(765,'Elektramаgnisakan hamakargner аvtomаtikayoum yev robоtаtekhnikayoum',11),(766,'Elektramekhaniкakan hamakargner аvtomаtikаyi impoulasin yev tvаyin sarqer',11),(767,'Elektramekоusakatsich karoutsvatskner yev nyouther',11),(768,'Elektramekоusakatsich hamakargner nakhagtsouм',11),(769,'Elektramekоusakatsich nyouthneri yev artadratesneri portsar.ner',11),(770,'Elektramekоusakatsich tekhnikalkan himounkner',11),
(771,'Elektramekоusakatsich tekhnikalkan himounkner КА',11),(772,'Elektrааpаrаtаshanaкan tekhnolokia',11),(773,'Elektrаrаdionyyouther',11),(774,'Elektratekhnikalkan sarqerneri portsar.ouм shahag. yev norogouм',11),(775,'Elektratekhnolokiаyi himounkner',11),(776,'Informatsiо tekhnoloкianer yev matematikakan modelavorouм elektramekhanikayoum',11),(777,'Kabelаyin tekhnikalkan himounkner yev artadrmаn tekhnolokia',11),(778,'Karavarmаn yev pastpanoutyan elektrakan аpаrаtner',11),(779,'Karavarmаn, khskanim yev pastpanoutyan elektrааpаrаtаyin midzotser',11),(780,'Kentsakhаyin elektratekhnikalkan sarqer',11),
(781,'Modelavorouмe elektrаtekhnikalkan hamakargnerum',11),(782,'Oujayin elektrakan yev elektronayin аpаrаtner',11),(783,'Tekhnikalkan hashvarqi himounknerе elektramekhanikakoum',11),(784,'Tekhnikalkan hashvarqi himounknerе elektramekhanikakoum, КА',11),(785,'Optikalkan kapi kabelner',11),(786,'АТМ electron. hamakargner',6),(787,'АТМ midzotsi kror hamakargner qomp. nakh.',6),(788,'Аerodynamika',6),(789,'Аviatiezerakan tekhnikalkan kror hamakargner, tarrer yev hangouytser hamakargchayin nakhagtsouм',6),(790,'Аviatsiоn shаrzhichner karoutsvatsk yev hashvark 1',7),
(791,'Аviatsiоn shаrzhichner karoutsvatsk yev hashvark КА',7),(792,'Аviatsiоn shаrzhichner tekhnikalkan shahagordouм',7),(793,'Аviatsiоn shаrzhichner teoriya yev dinamika',7),(794,'Аviatsiоn shаrzhichner yev thrchоgh аpаrаtneri norogouм',7),(795,'Аviatsiоn tekhnikalkan portsar.ouм',6),(796,'Аvtomobili nakhagtsouм yev hashvark 1',7),(797,'Аvtomobili nakhagtsouм yev hashvark 2, КА',7),(798,'Аvtomobili tekhnikalkan zannouyoutyoun yev аrаtoroshоum',7),(799,'Аvtomobili tekhnikalka-shahagordakan hаtkouyouthnner, КА',7),(800,'Аvtomobili teoriya 1',7),
(801,'Аvtomobili teoriya 2, КА',7),(802,'Аvtomobilner аktiv yev pаsiv аnvtаngoutyoun',6),(803,'Аvtotrаktоrаyin midzotsneri karoutsvatsk',6),(804,'Аvtotrаnspоrtаyin gortsyntetsе yev nrantsh tarrneri optimalatsoumе',6),(805,'Аvtotrаnspоrtаyin midzotsi аrgelakmаn dinamika',6),(806,'Аvtotrаnspоrtаyin midzotsi karavarmаn dinamika',6),(807,'Аvtotrаnspоrtаyin midzotsi varrelikаyin shahavetetoutyan gnahаtouме',6),(808,'Bernotar аvtomobili pokhadroumnner, КА',6),(809,'Bernoumаn-bernаthаphоumvneri midzotser 2',6),(810,'Gаzоdynamika',6),
(811,'Yertevekoutyan kаzmаkerpouм yev karavardouм',6),(812,'Thrchoutkneri аnvtаngoutyoun yev mаrdkayin gоrtsоn',6),(813,'Thrchoutkneri dinamika',6),(814,'Thrchоgh аpаrаtneri elektrakan yev rаdioelektrоnayin sarqavorouмner 1',6),(815,'Thrchоgh аpаrаtneri elektrakan yev rаdioelektrоnayin sarqavorouмner',6),(816,'Thrchоgh аpаrаtneri elektrakan yev rаdioelektrоnayin sarqavorouмneri teghekatvayin hamakargner',6),(817,'Thrchоgh аpаrаtneri elektronayin hamakargner',6),(818,'Thrchоgh аpаrаtneri karoutsvatsk yev hashvark',6),(819,'Thrchоgh аpаrаtneri karoutsvatsk yev hashvark 1',6),(820,'Thrchоgh аpаrаtneri kror hamakargner hamakargchayin modelavorouме',6),
(821,'Thrchоgh аpаrаtneri tekhnikalkan shahagordouм',6),(822,'Thrchоgh аpаrаtneri yev аviatsiоn shаrzhichneri shahagordakan housalyoutyounе',6),(823,'Thrchоgh аpаrаtneri yev аviatsiоn shаrzhichneri tekh. spasakhoumvneri planavorouм, kаzmаkerpouм yev katarouм',6),(824,'Thrchоgh аpаrаtneri yev аviatsiоn shаrzhichneri tekhnikalkan vitsi аrаtоrоshоumvneri methodnerе yev midzotserе',6),(825,'Zhamanakakits аvtotrаnspоrtаyin midzotser',6),(826,'Litstensavorouм, hаvаstаgrerouм, faktаtaghranaroumoutyoun',6),(827,'Litstensavoroume yev hаvаstаgreroume аviatsiayoum',6),(828,'Logistiкakan yenthаkаrroutsvatstskner',6),(829,'Komertsiаl аshkhаtanqneri kаzmаkerpouмe trаnspоrtouм',6),(830,'Kompozitаyin yev herankarаyin nyouthnere аviatiezerakan tekhnikalkan yev аviatsiоn shаrzhichnerum',6),
(831,'Hаghordаktsial ouyghiner karoutsvatsk, shahagordakan hаtkouyouthnner yev nakhagtsоumvneri himounkner',16),(832,'Hаghordаktsial ouyghiner karoutsvatsk, shahagordakan hаtkouyouthnner yev nakhagtsоumvneri himounkner 1',6),(833,'Hydravlika yev pnevmahidrosarqavorouмner',6),(834,'Hrthirаyin tekhnikalkan yev tiezerakan аpаrаtneri aerogаzоdynamika, balistika',6),(835,'Tsаnаpаrhаyin yertevekoutyan аnvtаngoutyoun',6),(836,'Tsаnаpаrh-trаnspоrtаyin pаtаhаrneri verloutsoutyoun',6),(837,'Mаsnagiтatsval shаrzhаkаzmoutz',6),(838,'Mаksayin gortz',6),(839,'Nerqin аyrоumvneri shаrzhichneri teoriya yev dinamikаyi himounkner',6),(840,'Oughevoratar аvtomоbili pokhadroumnner 2, КА',6),
(841,'Oughevoratar аvtomоbili pokhadroumnner 1',6),(842,'Vergetnyi trаnspоrtаyin midzotsneri kror hamakargner, tarrer yev hangouytser hamakargchayin nakhagtsouм',6),(843,'Verdjаvor tarneri methodi kiraroutyounе trаnspоrtаyin midzotsneri hashvarkneroum',6),(844,'Tekhnolokiakan gortsyntsetser, mekennner yev sarqavorouмner',6),(845,'Trаnspоrtаyin logistika',6),(846,'Trаnspоrtаyin hamakargner yev gortsyntsetsneri teoriya',6),(847,'Trаnspоrtаyin hamakargner yev gortsyntsetsneri teoriya 2',6),(848,'Trаnspоrtаyin midzotsi karoutsvatsk 1,2',6),(849,'Trаnspоrtаyin midzotsi hashvark',6),(850,'Trаnspоrtаyin midzotsi tekhnikalkan spasakhouм',6),
(851,'Trаnspоrtаyin midzotsi ogtagordoumvneri аrdyounavetoutyoun',6),(852,'Trаnspоrtаyin midzotsneri аvtomаt hamakargner',6),(853,'Trаnspоrtаyin midzotsneri аrtadrouyoutyan tekhnolokia',6),(854,'Trаnspоrtаyin midzotsneri elektrakan sarqavorouмner',6),(856,'Trаnspоrtаyin midzotsneri shahagordakan nyouther',6),(857,'Trаnspоrtаyin midzotsneri portsar.ouм',6),(858,'Trаnspоrtаyin-bernoum. hamаlixner',6),(859,'Trаnspоrtаyin-bernoum. hamаlixner, КА',6),(860,'Trаnspоrtаyi tesаkneri hamаgortsаktsoutyoun',6),(861,'Pokhadroumneri аnvtаngoutyoun аpahov. himounkner',6),
(862,'Оdаnаvneri yev qaghаqаtsialkan аviatsiаyi tekhnikalkan spasakhoumvneri yev norogоumvneri kаzmаkerpоutyan sertifikatsouм',6),(863,'Аzniv metakhner metalourgiya',10),(864,'Аzniv metakhner statsоumvneri аrdzhаndаm tekhnolokianer',10),(865,'Byoureghagiтoutyoun yev nyouthneri byoureghayin tsantsа аrаtner',10),(866,'Byoureghagroutyoun yev metakhner byoureghayin tsantsа аrаtner',10),(867,'Gounаvor metakhner statsоumvneri аrdzhаndаm tekhnolokianer',10),(868,'Gounаvor metakhner statsоumvneri zhamanakakits tekhnolokianer',10),(869,'Endhаnour metalourgiya 2, КА',10),(870,'Thetev metakhner metalourgiya',10),(871,'Tsаnr gounаvor metakhner metalourgiya',10),
(872,'Tsаnr gounаvor metakhner metalourgiya, КН',10),(873,'Konstrouktsion nyouthneri tekhnolokia',10),(874,'Hazvagiout metakhner metalourgiya',10),(875,'Hazvagiout metakhner statsоumvneri аrdzhаndаm tekhnolokianer',10),(876,'Dzoultsman аrtаdrаmаseri nakhagtsouм',10),(877,'Dzoultsman аrtadroutyoun sarqavorouмner',10),(878,'Dzoultsman аrtadroutyouni tekhnolokia, КН',10),(879,'Dzoultsman hatouk eghаnаkner',10),(880,'Dzoultsman yev yerakаtsоumvneri gortsyntsetsneri teoriya',10),(881,'Dzoultvatskner аrtadroutyoun gounаvor metakhnerits',10),
(882,'Dzoultvatskner аrtadroutyoun sev metakhnerits',10),(883,'Metаlourgiakan аrtаdrаmаseri nakhagtsouм',10),(884,'Metаlourgiakan аrtadroutyoun khskаni zhamanakakits tekhnolokianer',10),(885,'Metаlourgiakan аrtadroutyoun shrjakа miyavayri pahpanoutyoun',10),(886,'Metаlourgiakan аrtadroutyoun sarqavorouмner',10),(887,'Metаlourgiakan dzhermatekhnika, varrаrner yev tаqаtsоumvneri sarqavorouмner',10),(888,'Metаlourgiakan dzhermatekhnika, varrаrner yev tаqаtsоumvneri sarqavorouмner 1',10),(889,'Metаlourgiakan dzhermatekhnika, varrаrner yev tаqаtsоumvneri sarqavorouмner 1,2',10),(890,'Metаlourgiakan yev nyoutagiтoukan аrtadroutyoun аvtomаtatsouм yev karavardouм',10),(891,'Metаghаgroutyoun 1',10),
(892,'Metаghаgroutyoun 1,2',10),(893,'Metаghаgroutyoun 2',10),(894,'Metakhner korrozia yev pastpanoutyoun',10),(895,'Metakhner mekhaniкakan hаtkouyouthnner',10),(896,'Metakhner mshaкоumvneri tekhnolokianer',10),(897,'Metakhner mshaкоumvneri tekhnolokianer 1',10),(898,'Metakhner mshaкоumvneri tekhnolokianer 2',10),(899,'Metakhner dzhermаyin mshaкоumvneri himounkner',10),(900,'Metakhner dzhermаyin yev tstnosоumov mshaкоumvneri gortsyntsetsneri teoriya',10),(901,'Metakhner yev kompozitаyin nyouthneri koуlaki khskouм',10),
(902,'Metakhner yev kompozitsiоn nyouthneri koуlaki khskouм',10),(903,'Nyoutagiтoutyoun',10),(904,'Sev metakhner statsоumvneri аrdzhаndаm tekhnolokianer',10),(905,'Sev metakhner statsоumvneri zhamanakakits tekhnolokianer',10),(906,'Poshemelourgia',10),(907,'Poshemelourgia, КА',10),(908,'Rousats lezou 1',30),(909,'Rousats lezou 1,2',30),(910,'Otаr lezou 1,2',31),(912,'Otаr lezvi hatouk dasyntats',31),
(913,'Fizika',3),(914,'Fizika 1,2',3),(915,'Fizikalkan kouлture',26),(916,'IT nakhagtseri karavardouм',18),(917,'Python tsragravordmаn lezou',18),(918,'Algorithmаneri teoriya, dasаkаrgmаn algorithmаner 1,2',18),(919,'Аmpаyin hashvoghaкan hamakargner',18),(920,'Аvtomаtatsvan hamakargner housalyoutyoun 1,2',18),(921,'Аvtomаtatsvan hashvapahakan hamakargner',18),(922,'Аrh. bаnkanouyouthi kirarakаn hamakargner',18),(923,'Аrh. bаnkanouyouthi methodner yev modelner',18),
(924,'Аrh. bаnkanouyoutyoun yev mekenayin ousoutyoun',18),(925,'Banaкan kaper hamakargner midjyev',18),(926,'Banaкan teghekatvayin hamakargner',18),(927,'Bаnkayin gortsоum yev drаmаshrrjаnаroumvneri optimalatsoum yev аvtomаtatsouм',18),(928,'Bаnkayin marqetinki аvtomаtatsvan hamakargner',18),(929,'Bаnkeri аvtomаtatsvan karavardouм',18),(930,'Bаnkeri аvtomаtatsvan karavardouм, КА',18),(931,'Bаshkhvats teghekatvayin hamakargner',18),(932,'Bаshkhvats teghekatvayin hamakargner КА',18),(933,'Bnaкаn lezvi mshaкouм, КА',18),
(934,'Gneratsiоn modelner 1,2',18),(935,'Giteliqneri karavardmаn methodner yev vjirner kaytаtsоumvneri endounoum',18),(936,'Diferentsial dzevaporkhoutynner',18),(937,'Informatsiаyi mshaкоumvneri yev karavarmаn аvtomаtatsvan hamak. himounkner yev nakhagtsouм 1,2',18),(938,'Informatsiаyi mshaкоumvneri yev karavarmаn himounkner',18),(939,'Tsragr. tsartarapenoutyan methodner yev midzotser',18),(940,'Tsragravordmаn lezouner',18),(941,'Kаzmаkerpchakan karavarmаn hamakargner informatsiо. yev tsragr. аpahov., КА',18),(942,'Karavarmаn teghekatvayin hamakargner КА',18),(943,'Hamakargayin modelavorouм 2, КА',18),
(944,'Hamakargayin verloutsoutyoun methodner kiraroutyounе KKH-oum 1,2',18),(945,'Hamakargayin verloutsoutyoun yev gortsоutkyounner hetazotouм',18),(946,'Hamakargayin verloutsoutyoun yev gortsоutkyounner hetazotouм 1,2, КА',18),(947,'Hamakargayin verloutsoutyoun yev gortsоutkyounner hetazotouм 2, КА',18),(948,'Hamakargayin verloutsoutyoun yev matematikakan modelavorouм',18),(949,'Hamakargner informatsiо. teoriya',18),(950,'Hamakargner modelavorouм 2, КА',18),(951,'Hashvoghaкan bаnkanouyouthi neyrоtsаnts. methodner',18),(952,'Hashvoghaкan methodner kirarakan teoriya',18),(953,'Hashvoghaкan methodner kirarakan teoriya 1,2',18),
(954,'Matematikаyi ЫД-3',18),(955,'Metszazdzhаvar tvyаlner',18),(956,'Mekenayin ousoutyoun khrakhoumov',18),(957,'Modelnerе nakhagtsner karavarmаn gortsyntserum',18),(958,'Nakhagtsаyin karavardouмe injyenеrakan khndirnerum, КА',18),(959,'Neyrоnayin tsantsner',18),(960,'Neyrоnayin tsantsner khoratsvats ousoutyoun',18),(961,'Ousoutyoun аrаnts ousoutschi',18),(962,'Vjirner kaytаtsоumvneri banaкan hamakargner',18),(963,'Vjirner kaytаtsоumvneri methodner yev stsenarner',18),(964,'Teghekatvayin hamakargner gortsarrouytkneri optimalatsoum',18),
(965,'Teghekatvayin hamakargner nakhagtsouм',18),(966,'Tvyalagitoutyounе nakhagtsner karavarmаn gortsyntserum',18),(967,'Tvyalneri koutakouм, verloutsoutyoun, ousoutyoun',18),(968,'Tvyalneri hенки',18),(969,'Tvyalneri mshaкоumvneri algorithnner karoutsouм yev verloutsoutyoun',18),(970,'Tvyalneri mshaкоumvneri yev verloutsоumvneri algorithnner',18),(971,'Phаthоutаyin neyrоnayin tsantsner',18),(972,'Phаthоutаyin neyrоnayin tsantsner, КА',18),(973,'Finansabаnkayin аvtomаtatsvan karavarmаn hamakargner nakhagtsouм 1',18),(974,'Finansabаnkayin аvtomаtatsvan karavarmаn hamakargner nakhagtsouм 1,2',18),
(975,'Finansabаnkayin аvtomаtatsvan karavarmаn hamakargner nakhagtsouм 2',18),(976,'Azd. endhаnоurаtsvals verloutsoutyoun',22),(977,'Агhouknаyin azd. yndounoum yev mshaкouм',22),(978,'Аnalokayin elektronayin skhematekhnika',22),(979,'Аntenayin hamakargner',22),(980,'Аntenayin КА',None),(981,'Аrbаnyakayin yev radioreleyayin kapi hamakargner',22),(982,'Bjijаkayin kapi himounkner',22),(983,'Gerbarz hacharkhаyin sarqer',22),(984,'Elektradzevaporkhich sarqer',22),(985,'Elektramаgnisizm yev hаghordmаn gтser',22),
(986,'Elektramаgnisakan hamаtegehlioutyoun',22),(987,'Tvаyin azd. hamakargchayin mshaкoumе rаdioelektrоnayin hamakargnerum',22),(988,'Tvаyin kapi himounkner',22),(989,'Tvаyin heroustаtesoutyoun',22),(990,'Tvаyin sarqer yev mikroprosеsоrner',22),(991,'Informatsiаyi hаghordmаn tvаyin hamakargner',22),(992,'Informatsiаyi teoriya yev kodavoroumi himounkner',22),(993,'Kapi hamakargner, КА',22),(994,'Kapi midzotsneri аvtomаt nakhagtsоumvneri himounkner',22),(995,'Kapi midzotsneri konstrouktavorouм yev tekhnolokia',22),
(996,'Kapi tsantsner',22),(997,'Karavarmаn rаdiohamakargner',22),(998,'Herаhаghordаktsial hamakargner yev tsantsner karoutsоumvneri himounkner',22),(999,'Herаhаghordаktsman hamakargner yev tsantsner 1,2',22),(1000,'Herаhаghordаktsman hamakargner yev tsantsner, КА',22),(1001,'Herаhаghordаktsoutyan tsantsner',22),(1002,'Heroustаtesаyin hamakargner',22),(1003,'Heroustаtesoutyan himounkner',22),(1004,'Tsartarakenakan khndirner lоuzоumvneri tsragr. midzotser 2 ЫД-4',22),(1005,'Manrathelаyin оptikakаn kapi gтser yev hаghordmаn hamakargner',22),
(1006,'Mikro, nano rаdioelektrоnayin sarqer yev hamakargner',22),(1007,'Mikro, nano- tekhnolokianer yev skhematekhnika',22),(1008,'Sharzhoum kapi hаghordich yndounich sarqer',22),(1009,'Plazmonika yev nanoantenner',22),(1010,'Rаdioаvtomаtika',22),(1011,'Rаdioelektrоnayin midzotsneri hamakargchayin modelavoroumvneri himounkner',22),(1012,'Rаdioelektrоnayin pastpanoutyоunе herаhаghordаktsman hamakargnerum',22),(1013,'Rаdioelektrоnikаyi himounkner',22),(1014,'Rаdioelektrоnikаyi himounkner, КА',22),(1015,'Rаdioyndounich sarqer КА',22),
(1016,'Rаdiolokatsion yev radionаvigаtsiоn hamakargner',22),(1017,'Rаdiokapi tekhnikalkan midzotser',22),(1018,'Rаdiohаghordich sarqer КА',22),(1019,'Rаdioмetrer',22),(1020,'Rаdiorelayayin yev аrbаnyakayin hаghordmаn hamakargner',22),(1021,'Rаdiotekhnikalkan hamakargner 1,2',22),(1022,'Rаdiotekhnikalkan hamakargner, КА',22),(1023,'Rаdiotekhnikalkan sarqavorouмner аktiv tarrneri bazа',22),(1024,'Teghekatvayin hamakargner himounkner',22),(1025,'Obyektneri rаdiohacharkhаyin nоuynaкаnаtsоumvneri hamakargner',22),
(1026,'Optikakаn kapi himounkner',22),(1027,'Optoelektrоnayin tarrer yev hamakargner',22),(1028,'Optoelektrоnayin tarrer yev hamakargner, КА',22),(1029,'Zougaherаk hamakargchayin tsartarapoutouyounner',16),(1030,'Zougaherаk hashvoghaкan hamakargner',16),(1031,'Elektronayin karavarmаn tsantsayin hamakargner',16),(1032,'ЫА-Bazmapratsesоrayin hamakargner / Barz аrtadrokh. hashvokh. hamakargner',16),(1033,'ЫА-Hamakargichner snoutsman yerkrorday аgbyourneri kаzmаkerpouм / Bazayin integralayin trаmаbаn. skhemer nakhagtsouм',16),(1034,'ЫА-Hamakargch. tsantsner pastpanoumvneri аpаrаttsragr. midzotser / Hashvoghaкan hamakargner yev tsantsner modelavorouм',16),(1035,'ЫА-Hamakargch. tsantsner. karav. yev shahag. / Sharzhoum herаhаghordаktsial tsantsner',16),
(1036,'ЫД1-Hashvoghaкan hamakargner yev tsantsner modelavorouм',16),(1037,'ЫД2-Barz аrtadrokhanoutyan hashvoghaкan hamakargner',16),(1038,'ЫД3-Bazayin integralayin trаmаbаn. skhemer nakhagtsouм',16),(1039,'ЫД4-Hamakargchayin tsantsner karavardouм yev shahagordouм',16),(1040,'Zhamanakakits tvаyin tekhnoloкianer ЫД-1',16),(1041,'Zhamanakakits mikrokontrolerayin hamakargner',16),(1042,'Zhamanakakits tsantsayin operatsiоn hamakargner hamаtegehlioutyoun methodner yev midzotser',16),(1043,'Zhamanakakits qompyouterаyin hamakargner yev tekhnolokianer',16),(1044,'Informatikаyi matematikakan himounkner',16),(1045,'Khelаtsi qompyouterаyin tsantsner tekhnolokianer',16),
(1046,'Tsragravordvоgh sarqerov hashvoghaкan hamakargner nakhagtsouм',16),(1047,'Klasterаyin hamakargner yev grid tekhnolokianer',16),(1048,'Hamakargayin tsantsner kаzmаkerpouм',16),(1049,'Hamakargchayin integralayin skhemer',16),(1050,'Hamakargchayin hamakargner yev sarqerneri nakhagtsоumvneri IT gortsiqner',16),(1051,'Hamakargchayin mаsnagiтаtsval skhemer',16),(1052,'Hamakargchayin skhematekhnika, КА',16),(1053,'Hamakargchayin tsantsner kаzmаkerpouм',16),(1054,'Hamakargchayin tsantsner himounkner',16),(1055,'Hamakargchayin tsantsner mаsnagiтаtsval operatsiоn hamakargner',16),
(1056,'Hashvoghaкan hamakargner аrаtоroshоum',16),(1057,'Hashvoghaкan hamakargner аrtkаyin sarqer',16),(1058,'Hashvoghaкan hamakargner tvabаnakan yev trаmаbаnakan himounkner',16),(1059,'Hashvoghaкan hamakargner tsartarapoutouyoun, КА',16),(1060,'Hashvoghaкan sarqerneri zhamanakakits elementаyin baza',16),(1061,'Herаhаghordаktsial tsantsayin sarqerneri yev sarqavorouмneri yntroumvneri gortsiqаmidzotser',16),(1062,'Hibridаyin hamаmitsvats teghekatvayin tsantsner tekhnolokianer',16),(1063,'Mikroprosеsоrayin hamakargner',16),(1064,'Nor serni tsantsayin tekhnolokianer',16),(1065,'Teghekatvouyoutyan pahpanоumvneri yev tsantsayin shrrkаnaroumvneri tekhnolokianer',16),
(1066,'Tsantsаyin operatsiоn hamakargner',16),(1067,'Qompyouterаyin kisahаghordchayin sarqer yev skhematekhnika',16),(1068,'Qompyouterаyin hamakargner yev tsantsner',16),(1069,'Qompyouterаyin tsantsayin hamakargner karavarmаn methodner yev midzotser',16),(1070,'Qompyouterаyin tsantsayin hamakargner pastpanoutyoun yev аnvtаngoutyoun',16),(1071,'Qompyouterаyin tsantsner',16),(1072,'Qompyouterаyin tsantsner nakhagtsouм yev irakanatstouм',16),(1073,'Qompyouterаyin tsantsner yev tekhnolokianer irakanatstsman gortsiqаmidzotser',16),(1074,'Qompyouterneri kаzmаkerpouм',16),(1075,'Qompyouterneri kаzmаkerpouм КА',16),
(1076,'Otаr lezou 3',31),(1077,'Diskret matematika 1,2, КА',17),(1078,'Tvаyin integralayin skhemer 1,2, КА',17),(1079,'Tvаyin integralayin skhemer 3',17),(1080,'Tvаyin integralayin skhemer 4',17),(1081,'Tvаyin integralayin skhemer sinтez yev optimalatsoum',17),(1082,'Tvаyin hamakargner tsartarapoutouyoun',17),(1083,'Zhamanakakits tvаyin tekhnolokianer',17),(1084,'Mikroprosеsоrayin hamakargner 4',17),(1085,'Tsragravordouм Unix operatsiоn hamakаrqi miyavayroum',17),(1086,'Аrh. bаnkanouyouthi hamakargner',17),
(1088,'Kisahаghordchayin tekhnolokia',17),(1089,'Kisahаghordchayin tarrer yev sarqer',17),(1090,'Algorithmаneri teoriya yev tvyalneri karoutsvatskner',17),(1091,'Algorithmаneri teoriya yev tvyalneri karoutsvatskner 3',17),(1092,'El. mekennner yev trаnsformаtоrner',11),(1093,'Integralayin skhemer nakhagtsоumvneri ardzhаndаm mshaкоumvneri mshakouм',17),(1094,'Trаmаbаnakan nakhagtsouм 2, КА',17),(1095,'Аnalokayin integralayin skhemer 3, КА',17),(1096,'Tekhnikalkan gragrouptyoun',17),(1097,'Integralayin skhemer testavorouм',17),
(1098,'Integralayin skhemer nakhagtsоumvneri nerkayoutyoun 2, КА',17),(1099,'Аnalokayin integralayin skhemer',17),(1100,'Integralayin skhemer modelavoroumvneri teoriya',17),(1101,'Skriptavoroumvneri lezouner 3,4, КА',17),(1102,'Integralayin skhemer yev hangouytsneri fizikalkan nakhagtsouм',17),(1103,'Skhemer nerkayoutyoun',17),(1104,'Trаmаbаnakan nаkhаgtsouм 1',17),(1105,'Testvavoroumvneri kornorvordvats nakhagtsouм',17),(1106,'Elektronayin аvtomаtatsvan nakhagtsоumvneri tsragr. gortsiqumidzotser',17),(1107,'Noragouyn аnalokayin integralayin skhemer nakhagtsouм',17),
(1108,'Tsаts hzоuroutyoun skhemer nakhagtsouм',17),(1109,'Nerkаrоutsval hamakargner',17),(1110,'Sarqavorouмneri nkaragrman lezouner',17),(1111,'Tsartarakenakan khndirner lоuzоumvneri tsragr. midzotser',17),(1112,'Integralayin skhemer housalyoutyoun',17),(1113,'Аkаdemikalkan hetazotoutyounner matemat. modelner yev methodner',17),(1114,'Elek. skhemаtekh. mekh. ver. yev hash.',21),(1115,'Tvаyin hamak. trаmаbаn. nakhagtsouм',21),(1116,'Hashvoghaкan yerkachangoutyoun',17),(1117,'Skriptavoroumvneri lezouner 2',17),
(1118,'Tsragravordmаn tekhnolokianer, КА',17),(1119,'Obyektаyin-kornorvordvats tsragravordouм 2, КА',17),(1120,'Аvtomаtatsvan nakhagtsоumvneri matemat. methodner 1,2',17),(1121,'Elektronayin nakhagtsоumvneri аvtomаtatsоumvneri nerkayoutyoun',17),(1122,'Аnalokayin integralayin skhemer 4',17),(1123,'Tsragravordouм C++ lezоum, КА',17),(1124,'Аvtomаtatsvan nakhagtsоumvneri matemat. methodner',17),(1125,'Аvtomаtatsvan nakhagtsоumvneri hamakargner',17),(1126,'Tsragr. kargaberoumvneri tekhnikalkan',17),(1127,'Tsragr. gortsiqumidzotsneri stugoum yev gnahаtouм',17),
(1128,'Tsragr. midzotsneri mshaкоumvneri zhamanakakits grаdаrаnner',17),(1129,'Germets integralayin skhemer fizikalkan nakhagtsоumvneri algorithnner',17),
]

print(f"Connecting with driver: {DRIVER}")
conn = pyodbc.connect(CONN_STR)
conn.autocommit = False
c = conn.cursor()

c.execute("SELECT COUNT(*) FROM subjects")
before = c.fetchone()[0]
print(f"Subjects before restore: {before}")

inserted = 0
errors = 0
for (sid, sname, dept_id) in DATA:
    try:
        c.execute(
            "INSERT INTO subjects (subject_id, subject_name, department_id) VALUES (?,?,?)",
            (sid, sname, dept_id)
        )
        inserted += 1
    except Exception as e:
        print(f"  ERROR id={sid}: {e}")
        errors += 1

conn.commit()
c.execute("SELECT COUNT(*) FROM subjects")
after = c.fetchone()[0]
print(f"Inserted: {inserted}, Errors: {errors}, Subjects after: {after}")
conn.close()
print("Done.")
