import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "en" | "hy";

export const T = {
  en: {
    // App & Navigation
    appName: "UNICOST",
    appSub: "Financial Intelligence",
    overview: "OVERVIEW",
    financials: "FINANCIALS",
    data: "DATA",
    manage: "MANAGE",
    online: "Online",
    financeAdmin: "Finance Admin",
    dashboard: "Dashboard",
    costReports: "Cost Reports",
    income: "Income",
    analytics: "Analytics",
    institutes: "Institutes",
    departments: "Departments",
    groups: "Groups",
    subjects: "Subjects",
    professions: "Professions",
    // Dashboard
    dashboardTitle: "Dashboard",
    dashboardSub: "University-wide financial overview",
    totalStudents: "Total Students",
    allStudentsCount: "All students count",
    lecturerSalary: "Lecturer Salary",
    teachingCosts: "Teaching costs total",
    totalAllCosts: "Total All Costs",
    fullExpenditure: "Full expenditure",
    totalIncome: "Total Income",
    fromTuition: "From tuition fees",
    costVsIncome: "Cost vs Income by Institute",
    costBreakdown: "Cost Breakdown by Institute",
    valuesInMillions: "Values in millions AMD",
    stackedComponents: "Stacked components in millions AMD",
    fullCostBreakdown: "Full Cost Breakdown",
    allComponents: "All calculated components per institute",
    // Common
    institute: "Institute",
    department: "Department",
    group: "Group",
    code: "Code",
    degree: "Degree",
    eduType: "Edu Type",
    students: "Students",
    allCosts: "All Costs",
    profit: "Profit",
    tuitionFee: "Tuition Fee",
    avgTuition: "Avg Tuition",
    costPerStudent: "Cost / Student",
    profitability: "Profitability Ratio",
    yearlyLoad: "Yearly Load",
    hourlySalary: "Hourly Salary",
    monthlySalary: "Monthly Salary",
    avgRate: "Avg Rate",
    yearlyHours: "Yearly Hours",
    sem1Hours: "Sem 1 Hours",
    sem2Hours: "Sem 2 Hours",
    paid: "Paid",
    free: "Free",
    profession: "Profession",
    area: "Area (m2)",
    lecturer: "Lecturer",
    variable: "Variable",
    fixed: "Fixed",
    utility: "Utility",
    other: "Other",
    allowance: "Allowance",
    // Buttons & Actions
    addRow: "Add Row",
    update: "Update",
    deleteAll: "Delete All",
    importFile: "Import",
    exportFile: "Export",
    refresh: "Refresh",
    search: "Search...",
    cancelBtn: "Cancel",
    deleteBtn: "Delete",
    importClose: "Close",
    save: "Save",
    edit: "Edit",
    actions: "Actions",
    noRecordsFound: "No records found",
    cancelEdit: "Cancel",
    // Cost Reports
    costReportsTitle: "Cost Reports",
    costReportsSub: "Query every calculated value from the database",
    reportType: "Report Type",
    instituteFilter: "Institute",
    allInstitutes: "All Institutes",
    highestValue: "Highest Value",
    singleInstitute: "Single institute",
    detail: "Detail",
    byInstitute: "by Institute",
    records: "records",
    record: "record",
    fullCostBreakdownLabel: "Full Cost Breakdown",
    fullCostBreakdownDesc: "All cost components per institute in one view",
    lecturerSalaryLabel: "Lecturer Salary",
    lecturerSalaryDesc: "SUM(hours_yearly x avg_hourly_rate) per institute",
    variableAllowanceLabel: "Variable Allowance",
    variableAllowanceDesc: "yearly_salary + group_count x constant",
    fixedAllowanceLabel: "Fixed Allowance",
    fixedAllowanceDesc: "student_count x 732,000,000 / all_students",
    utilityCostLabel: "Utility Cost",
    utilityCostDesc: "(area + [10] + [21] + [3]) x 1524.88",
    otherCostsLabel: "Other Costs",
    otherCostsDesc: "(lecturer + variable + fixed + utility) x 0.15 / 0.84",
    allCostsTotalLabel: "All Costs (Total)",
    allCostsTotalDesc: "lecturer_salary + allowance_costs",
    // Income
    incomeTitle: "Income Reports",
    incomeSub: "student_count x tuition_fee aggregated by group, department, and institute",
    level: "Level",
    byInstituteLvl: "By Institute",
    byDepartment: "By Department",
    byGroup: "By Group",
    avgPerStudent: "Avg per Student",
    enrolled: "Enrolled",
    incomePerStudent: "Income per student",
    incomeDetail: "Income Detail",
    // Analytics
    analyticsTitle: "Analytics",
    analyticsSub: "Per-student cost, profit and profitability ratio",
    totalCosts: "Total Costs",
    allExpenditure: "All expenditure",
    totalProfit: "Total Profit",
    surplus: "Surplus",
    deficit: "Deficit",
    avgCostStudent: "Avg Cost / Student",
    universityAvg: "University average",
    tuitionRevenue: "Tuition revenue",
    profitLoss: "Profit / Loss per",
    surplusLabel: "Surplus",
    deficitLabel: "Deficit",
    costPerStudentChart: "Cost per Student",
    amdPerStudent: "AMD per student",
    analyticsDetail: "Analytics Detail",
    formulasTitle: "Formulas & Definitions",
    hideFormulas: "Hide",
    showFormulas: "Show",
    exportCSV: "Export CSV",
    // Manage pages
    instituteSub: "Add, edit or remove institutes",
    departmentSub: "Add, edit or remove departments",
    groupSub: "Add, edit or remove student groups",
    subjectSub: "Add, edit or remove subjects",
    professionSub: "Add, edit or remove professions",
    institutesViewSub: "All registered institutes",
    departmentsViewSub: "Salary and workload data per department",
    groupsViewSub: "Student groups with enrollment and tuition data",
    subjectsViewSub: "Course hour assignments by department",
    professionsViewSub: "Academic programs offered per institute",
    addNewInstitute: "Add New Institute",
    addNewDepartment: "Add New Department",
    addNewGroup: "Add New Group",
    addNewSubject: "Add New Subject",
    addNewProfession: "Add New Profession",
    editRecord: "Editing record",
    // Import
    importTitle: "Import",
    importUploadText: "Click to upload CSV or Excel file",
    importMustInclude: "Must include headers",
    importRequiredCols: "Required columns (CSV / Excel):",
    importDownloadTpl: "Download Excel Template",
    importSuccess: "Successfully imported",
    importRecords: "records.",
    importFailed: "Import failed",
    // Confirm
    areYouSure: "Are you sure?",
    deleteRowMsg: "This record will be permanently deleted.",
        deleteAllMsg: "ALL records in this table will be permanently deleted.",
        deleteSelectedMsg: "Selected records will be permanently deleted.",
        departmentCode: "Department Code",
    // Calculated fields
    avgHourlyRateCalc: "Avg Hourly Rate (auto-calculated)",
    avgHourlyRateFormula: "ROUND((12 x monthly_salary) / yearly_load, 0)",
    hoursYearlyCalc: "Hours Yearly (auto-calculated)",
    hoursYearlyFormula: "hours_sem1 + hours_sem2",
    // Settings
    settings: "Settings",
    settingsSub: "Database connection configuration",
    dbServer: "Server",
    dbDatabase: "Database",
    dbUsername: "Username",
    dbPassword: "Password",
    dbEncrypt: "Encrypt connection",
    dbTrustCert: "Trust server certificate",
    dbTimeout: "Connection timeout (sec)",
    testConnection: "Test Connection",
    saveSettings: "Save Settings",
    settingsSaved: "Settings saved successfully.",
    connectionOk: "Connection successful.",
    connectionFailed: "Connection failed.",
    dbError: "Database Error",
    dbErrorMsg: "Cannot connect to the database. Please check your connection settings.",
    goToSettings: "Go to Settings",
    // Form
    instituteName: "Institute Name",
    instituteCode: "Code",
    departmentName: "Name",
    groupName: "Group Name",
    subjectName: "Subject Name",
    professionName: "Profession",
    selectInstitute: "Institute",
    selectDept: "Department",
    selectProfession: "Profession",
    selectOption: "— Select —",
    // Formulas
    formulas: {
      institute: {
        title: "Institute Level Formulas",
        items: [
          { label: "Cost per Student",    formula: "All Costs / Student Count",                       note: "Total expenditure divided by number of students enrolled in the institute" },
          { label: "Income",              formula: "SUM(student_count x tuition_fee)",                note: "Sum of each group's student count multiplied by their tuition fee" },
          { label: "Profit",              formula: "Income - All Costs",                              note: "Positive = surplus, Negative = deficit" },
          { label: "Avg Tuition Fee",     formula: "SUM(student_count x tuition_fee) / student_count", note: "Weighted average tuition fee per student" },
          { label: "Profitability Ratio", formula: "All Costs / Avg Tuition Fee",                    note: "How many average tuition fees needed to cover costs. Ratio > 1 means deficit." },
        ],
      },
      department: {
        title: "Department Level Formulas",
        items: [
          { label: "Dept Cost",        formula: "All Costs x (Dept Students / Inst Students)", note: "Institute costs distributed proportionally by department student share" },
          { label: "Cost per Student", formula: "Dept Cost / Dept Student Count",              note: "Proportional cost per student in this department" },
          { label: "Income",           formula: "SUM(student_count x tuition_fee)",            note: "Sum of income from all groups linked to this department" },
          { label: "Profit",           formula: "Income - Dept Cost",                          note: "Positive = surplus, Negative = deficit for this department" },
        ],
      },
      group: {
        title: "Group Level Formulas",
        items: [
          { label: "Group Cost",       formula: "All Costs x (Group Students / Inst Students)", note: "Institute costs distributed proportionally by group student share" },
          { label: "Cost per Student", formula: "Group Cost / Group Student Count",             note: "Proportional cost per student in this group" },
          { label: "Income",           formula: "student_count x tuition_fee",                  note: "Direct income from this group's students" },
          { label: "Profit",           formula: "Income - Group Cost",                          note: "Positive = surplus, Negative = deficit for this group" },
          { label: "Profitability",    formula: "Group Cost / (student_count x tuition_fee)",   note: "Ratio < 1 means profitable. Ratio > 1 means costs exceed earnings." },
        ],
      },
    },
  },
  hy: {
    // App & Navigation
    appName: "UNICOST",
    appSub: "Ֆինանսական գրագիտություն",
    overview: "ԸՆԴՀԱՆՈՒՐ ԱԿՆԱՐԿ",
    financials: "ՖԻՆԱՆՍՆԵՐ",
    data: "ՏՎՅԱԼՆԵՐ",
    manage: "ԽՄԲԱԳՐՈՒՄ",
    online: "Առցանց",
    financeAdmin: "Ֆինանսների ադմինիստրատոր",
    dashboard: "Կառավարման վահանակ",
    costReports: "Ծախսերի հաշվետվություններ",
    income: "Եկամուտ",
    analytics: "Վերլուծություններ",
    institutes: "Ինստիտուտներ",
    departments: "Ամբիոններ",
    groups: "Խմբեր",
    subjects: "Առարկաներ",
    professions: "Մասնագիտություններ",
    // Dashboard
    dashboardTitle: "Կառավարման վահանակ",
    dashboardSub: "Համալսարանի ֆինանսական ընդհանուր ակնարկ",
    totalStudents: "Ուսանողների ընդհանուր թիվը",
    allStudentsCount: "Բոլոր ուսանողների թիվը",
    lecturerSalary: "Դասախոսի աշխատավարձ",
    teachingCosts: "Ուսուցման ծախսերի ընդհանուր գումար",
    totalAllCosts: "Ծախսերի ընդհանուր գումար",
    fullExpenditure: "Ամբողջական ծախս",
    totalIncome: "Ընդհանուր եկամուտը",
    fromTuition: "Ուսման վարձից",
    costVsIncome: "Ծախսեր ընդդեմ եկամտի՝ ըստ ինստիտուտի",
    costBreakdown: "Ծախսերի բաշխում ըստ ինստիտուտի",
    valuesInMillions: "Արժեքները մլն AMD-ով",
    stackedComponents: "Կուտակված բաղադրիչներ մլն AMD-ով",
    fullCostBreakdown: "Ծախսերի ամբողջական բաշխում",
    allComponents: "Բոլոր հաշվարկված բաղադրիչները ըստ ինստիտուտի",
    // Common
    institute: "Ինստիտուտ",
    department: "Ամբիոն",
    group: "Խումբ",
    code: "Կոդ",
    degree: "Աստիճան",
    eduType: "Կրթության տեսակ",
    students: "Ուսանողներ",
    allCosts: "Բոլոր ծախսերը",
    profit: "Շահույթ",
    tuitionFee: "Ուսման վարձ",
    avgTuition: "Միջին ուսման վարձ",
    costPerStudent: "Արժեք / Ուսանող",
    profitability: "Շահութաբերության գործակից",
    yearlyLoad: "Տարեկան ծանրաբեռնվածություն",
    hourlySalary: "Ժամային աշխատավարձ",
    monthlySalary: "Ամսական աշխատավարձ",
    avgRate: "Միջին դրույքաչափ",
    yearlyHours: "Տարեկան ժամեր",
    sem1Hours: "Կիսամյակ 1 ժամ",
    sem2Hours: "Կիսամյակ 2 ժամ",
    paid: "Վճարովի",
    free: "Անվճար",
    profession: "Մասնագիտություն",
    area: "Տարածք (մ2)",
    lecturer: "Դասախոս",
    variable: "Փոփոխական",
    fixed: "Հաստատուն",
    utility: "Կոմունալ",
    other: "Այլ",
    allowance: "Վերադիր",
    // Buttons & Actions
    addRow: "Ավելացնել տող",
    update: "Թարմացնել",
    deleteAll: "Ջնջել բոլորը",
    importFile: "Ներմուծել",
    exportFile: "Ներբեռնել",
    refresh: "Թարմացնել",
    search: "Որոնել...",
    cancelBtn: "Չեղարկել",
    deleteBtn: "Ջնջել",
    importClose: "Փակել",
    save: "Պահպանել",
    edit: "Խմբագրել",
    actions: "Գործողություններ",
    noRecordsFound: "Գրառումներ չեն գտնվել",
    cancelEdit: "Չեղարկել",
    // Cost Reports
    costReportsTitle: "Ծախսերի հաշվետվություններ",
    costReportsSub: "Հարցում կատարեք տվյալների բազայի ցանկացած հաշվարկված արժեքի համար",
    reportType: "Հաշվետվության տեսակ",
    instituteFilter: "Ինստիտուտ",
    allInstitutes: "Բոլոր ինստիտուտները",
    highestValue: "Առավելագույն արժեք",
    singleInstitute: "Մեկ ինստիտուտ",
    detail: "Մանրամասն",
    byInstitute: "ըստ ինստիտուտի",
    records: "գրառումներ",
    record: "գրառում",
    fullCostBreakdownLabel: "Ծախսերի ամբողջական բաշխում",
    fullCostBreakdownDesc: "Բոլոր ծախսային բաղադրիչները ըստ ինստիտուտի",
    lecturerSalaryLabel: "Դասախոսի աշխատավարձ",
    lecturerSalaryDesc: "ԳՈՒՄԱՐ(hours_yearly x avg_hourly_rate) ըստ ինստիտուտի",
    variableAllowanceLabel: "Փոփոխական վերադիր",
    variableAllowanceDesc: "yearly_salary + group_count x հաստատուն",
    fixedAllowanceLabel: "Հաստատուն վերադիր",
    fixedAllowanceDesc: "student_count x 732,000,000 / բոլոր_ուսանողները",
    utilityCostLabel: "Կոմունալ ծախս",
    utilityCostDesc: "(տարածք + [10] + [21] + [3]) x 1524.88",
    otherCostsLabel: "Այլ ծախսեր",
    otherCostsDesc: "(դasakhos + փofokhkan + hastatoun + komunal) x 0.15 / 0.84",
    allCostsTotalLabel: "Բոլոր ծախսերը (ընդամենը)",
    allCostsTotalDesc: "lecturer_salary + allowance_costs",
    // Income
    incomeTitle: "Եկամտի հաշվետվություններ",
    incomeSub: "student_count x tuition_fee՝ ամփոփված ըստ խմբի, ամբիոնի և ինստիտուտի",
    level: "Մակարդակ",
    byInstituteLvl: "Ըստ ինստիտուտի",
    byDepartment: "Ըստ ամբիոնի",
    byGroup: "Ըստ խմբի",
    avgPerStudent: "Միջինը մեկ ուսանողի հաշվով",
    enrolled: "Ուսումնառության մեջ ընդգրկվածները",
    incomePerStudent: "Եկամուտ մեկ ուսանողի հաշվով",
    incomeDetail: "Եկամտի մանրամասն",
    // Analytics
    analyticsTitle: "Վերլուծություններ",
    analyticsSub: "Մեկ ուսանողի արժեք, շահույթ և շահութաբերության գործակից",
    totalCosts: "Ընդհանուր ծախսերը",
    allExpenditure: "Բոլոր ծախսերը",
    totalProfit: "Ընդհանուր շահույթը",
    surplus: "Ավելցուկ",
    deficit: "Դեֆիցիտ",
    avgCostStudent: "Միջին արժեքը / ուսանող",
    universityAvg: "Համալսարանի միջին թիվը",
    tuitionRevenue: "Ուսման վարձի եկամուտը",
    profitLoss: "Շահույթ / Վնաս՝ ըստ",
    surplusLabel: "Ավելցուկ",
    deficitLabel: "Դեֆիցիտ",
    costPerStudentChart: "Մեկ ուսանողի արժեքը",
    amdPerStudent: "AMD մեկ ուսանողի հաշվով",
    analyticsDetail: "Վերլուծությունների մանրամասն",
    formulasTitle: "Բանաձևեր և սահմանումներ",
    hideFormulas: "Թաքցնել",
    showFormulas: "Ցուցադրել",
    exportCSV: "Ներբեռնել CSV",
    // Manage pages
    instituteSub: "Ավելացնել, խմբագրել կամ հեռացնել ինստիտուտները",
    departmentSub: "Ավելացնել, խմբագրել կամ հեռացնել ամբիոնները",
    groupSub: "Ավելացնել, խմբագրել կամ հեռացնել ուսանողական խմբերը",
    subjectSub: "Ավելացնել, խմբագրել կամ հեռացնել առարկաները",
    professionSub: "Ավելացնել, խմբագրել կամ հեռացնել մասնագիտությունները",
    institutesViewSub: "Բոլոր գրանցված ինստիտուտները",
    departmentsViewSub: "Աշխատավարձ և ծանրաբեռնվածություն ըստ ամբիոնի",
    groupsViewSub: "Ուսանողական խմբեր՝ ընդունելության և ուսման վարձի տվյալներով",
    subjectsViewSub: "Դասընթացի ժամաքանակի նշանակումներ ըստ ամբիոնի",
    professionsViewSub: "Ակադեմիական ծրագրեր ըստ ինստիտուտի",
    addNewInstitute: "Ավելացնել ինստիտուտ",
    addNewDepartment: "Ավելացնել ամբիոն",
    addNewGroup: "Ավելացնել խումբ",
    addNewSubject: "Ավելացնել առարկա",
    addNewProfession: "Ավելացնել մասնագիտություն",
    editRecord: "Խմբագրվում է գրառում",
    // Import
    importTitle: "Ներմուծել",
    importUploadText: "Սեղմեք CSV կամ Excel ֆայլ վերբեռնելու համար",
    importMustInclude: "Պետք է ներառի վերնագրեր",
    importRequiredCols: "Պահանջվող սյուներ (CSV / Excel).",
    importDownloadTpl: "Ներբեռնեք Excel ձևանմուշը",
    importSuccess: "Հաջողությամբ ներմուծվեց",
    importRecords: "գրառումներ։",
    importFailed: "Ներմուծումը ձախողվեց",
    // Confirm
    areYouSure: "Վստա՞հ եք։",
    deleteRowMsg: "Այս գրառումը ընդմիշտ կջնջվի։",
      deleteAllMsg: "ԲՈԼՈՐ գրառումները ընդմիշտ կջնջվեն։",
      deleteSelectedMsg: "Ընտրված գրառումները ընդմիշտ կջնջվեն։",
      departmentCode: "Ամբիոնի կոդ",
    // Calculated fields
    avgHourlyRateCalc: "Միջին ժամային դրույքաչափ (ավտոմատ հաշվարկ)",
    avgHourlyRateFormula: "ROUND((12 x ամսական_աշխ.) / տարեկան_ծանրաբ., 0)",
    hoursYearlyCalc: "Տարեկան ժամեր (ավտոմատ հաշվարկ)",
    hoursYearlyFormula: "hours_sem1 + hours_sem2",
    // Settings
    settings: "Կարգավորումներ",
    settingsSub: "Տվյալների բազայի կապի կարգավորում",
    dbServer: "Սերվեր",
    dbDatabase: "Տվյալների բազա",
    dbUsername: "Օգտատեր",
    dbPassword: "Գաղտնաբառ",
    dbEncrypt: "Կոդավորել կապը",
    dbTrustCert: "Վստահել սերվերի վկայականին",
    dbTimeout: "Կապի ժամանակ (վ)",
    testConnection: "Ստուգել կապը",
    saveSettings: "Պահպանել",
    settingsSaved: "Կարգավորումները պահպանված են։",
    connectionOk: "Կապը հաջողված է։",
    connectionFailed: "Կապը ձախողվեց։",
    dbError: "Տվյալների բազայի սխալ",
    dbErrorMsg: "Հնարավոր չէ միանալ տվյալների բազային։ Ստուգեք կապի կարգավորումները։",
    goToSettings: "Գնալ Կարգավորումներ",
    // Form
    instituteName: "Ինստիտուտի անվանումը",
    instituteCode: "Կոդ",
    departmentName: "Անվանումը",
    groupName: "Խմբի անվանումը",
    subjectName: "Առարկայի անվանումը",
    professionName: "Մասնագիտություն",
    selectInstitute: "Ինստիտուտ",
    selectDept: "Ամբիոն",
    selectProfession: "Մասնագիտություն",
    selectOption: "— Ընտրել —",
    // Formulas
    formulas: {
      institute: {
        title: "Ինստիտուտի մակարդակի բանաձևեր",
        items: [
          { label: "Մեկ ուսանողի արժեքը",         formula: "Բոլոր ծախսերը / Ուսանողների թիվը",                         note: "Ընդհանուր ծախսը բաժանված ինստիտուտում ընդգրկված ուսանողների թվի վրա" },
          { label: "Եկամուտը",                     formula: "ԳՈՒՄԱՐ(student_count x tuition_fee)",                      note: "Յուրաքանչյուր խմբի ուսանողների թիվը բազմապատկած ուսման վարձով" },
          { label: "Շահույթը",                     formula: "Եկամուտ - Բոլոր ծախսեր",                                  note: "Դրական = ավելցուկ, Բացասական = դեֆիցիտ" },
          { label: "Միջին ուսման վարձը",            formula: "ԳՈՒՄԱՐ(student_count x tuition_fee) / student_count",     note: "Կշռված միջին ուսման վարձ մեկ ուսանողի հաշվով" },
          { label: "Շահութաբերության գործակիցը",   formula: "Բոլոր ծախսեր / Միջին ուսման վարձ",                       note: "Քանի միջին ուսման վարձ է պետք բոլոր ծախսերը ծածկելու համար։ Գործ. > 1 նշանակում է դեֆիցիտ։" },
        ],
      },
      department: {
        title: "Ամբիոնի մակարդակի բանաձևեր",
        items: [
          { label: "Բաժնի արժեքը",            formula: "Բոլոր ծախսեր x (Ամբ. ուս. / Ինստ. ուս.)",  note: "Ինստիտուտի ծախսերը բաշխված համամասնորեն ըստ ամբիոնի ուսանողների բաժնի" },
          { label: "Մեկ ուսանողի արժեքը",     formula: "Բաժնի արժեք / Ամբ. ուսանողների թիվ",       note: "Համամասնական արժեք ամբիոնի մեկ ուսանողի հաշվով" },
          { label: "Եկամուտը",                 formula: "ԳՈՒՄԱՐ(student_count x tuition_fee)",       note: "Ամբիոնի հետ կապված բոլոր խմբերի եկամուտների գումար" },
          { label: "Շահույթը",                 formula: "Եկամուտ - Բաժնի արժեք",                    note: "Դրական = ավելցուկ, Բացասական = դեֆիցիտ ամբիոնի համար" },
        ],
      },
      group: {
        title: "Խmberi makardag banadzever",
        items: [
          { label: "Khmbаyi arjeqy",              formula: "Bolor tsakhser x (Khmb. ous. / Inst. ous.)", note: "Institouti tsakhsery bashkhvats hamamasnoroyen ysd khmberi ousanolneri bajni" },
          { label: "Mek ousanoli arjeqy",          formula: "Khmbаyi arjeq / Khmb. ousanolneri tv",      note: "Hamamasnorakan arjeq khmberi mek ousanoli hashvov" },
          { label: "Ekamouty",                     formula: "student_count x tuition_fee",                note: "Oudjaki ekamout ays khmberi ousanolnerits" },
          { label: "Shahouыty",                    formula: "Ekamout - Khmbаyi arjeq",                    note: "Drakan = aveltsouk, Batsasakan = deficit khmberi hamar" },
          { label: "Shahouytaberouttyan gortsak.",  formula: "Khmbаyi arjeq / (student_count x tuition_fee)", note: "Gortsak. < 1 = shahouytaber. Gortsak. > 1 = tsakhsy gerazantsoum e ekamouty" },
        ],
      },
    },
  },
} as const;

// ── Context ────────────────────────────────────────────────────────────
interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: typeof T.en | typeof T.hy;
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  setLang: () => {},
  t: T.en,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");
  return (
    <LangContext.Provider value={{ lang, setLang, t: T[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
